export const cityMunicipality = [
  { value: "ADAMS", label: "ADAMS" },
  { value: "BACARRA", label: "BACARRA" },
  { value: "BADOC", label: "BADOC" },
  { value: "BANGUI", label: "BANGUI" },
  { value: "CITY OF BATAC", label: "CITY OF BATAC" },
  { value: "BURGOS", label: "BURGOS" },
  { value: "CARASI", label: "CARASI" },
  { value: "CURRIMAO", label: "CURRIMAO" },
  { value: "DINGRAS", label: "DINGRAS" },
  { value: "DUMALNEG", label: "DUMALNEG" },
  { value: "BANNA (ESPIRITU)", label: "BANNA (ESPIRITU)" },
  { value: "LAOAG CITY (Capital)", label: "LAOAG CITY (Capital)" },
  { value: "MARCOS", label: "MARCOS" },
  { value: "NUEVA ERA", label: "NUEVA ERA" },
  { value: "PAGUDPUD", label: "PAGUDPUD" },
  { value: "PAOAY", label: "PAOAY" },
  { value: "PASUQUIN", label: "PASUQUIN" },
  { value: "PIDDIG", label: "PIDDIG" },
  { value: "PINILI", label: "PINILI" },
  { value: "SAN NICOLAS", label: "SAN NICOLAS" },
  { value: "SARRAT", label: "SARRAT" },
  { value: "SOLSONA", label: "SOLSONA" },
  { value: "VINTAR", label: "VINTAR" },
  { value: "ALILEM", label: "ALILEM" },
  { value: "BANAYOYO", label: "BANAYOYO" },
  { value: "BANTAY", label: "BANTAY" },
  { value: "BURGOS", label: "BURGOS" },
  { value: "CABUGAO", label: "CABUGAO" },
  { value: "CITY OF CANDON", label: "CITY OF CANDON" },
  { value: "CAOAYAN", label: "CAOAYAN" },
  { value: "CERVANTES", label: "CERVANTES" },
  { value: "GALIMUYOD", label: "GALIMUYOD" },
  {
    value: "GREGORIO DEL PILAR (CONCEPCION)",
    label: "GREGORIO DEL PILAR (CONCEPCION)",
  },
  { value: "LIDLIDDA", label: "LIDLIDDA" },
  { value: "MAGSINGAL", label: "MAGSINGAL" },
  { value: "NAGBUKEL", label: "NAGBUKEL" },
  { value: "NARVACAN", label: "NARVACAN" },
  { value: "QUIRINO (ANGKAKI)", label: "QUIRINO (ANGKAKI)" },
  { value: "SALCEDO (BAUGEN)", label: "SALCEDO (BAUGEN)" },
  { value: "SAN EMILIO", label: "SAN EMILIO" },
  { value: "SAN ESTEBAN", label: "SAN ESTEBAN" },
  { value: "SAN ILDEFONSO", label: "SAN ILDEFONSO" },
  { value: "SAN JUAN (LAPOG)", label: "SAN JUAN (LAPOG)" },
  { value: "SAN VICENTE", label: "SAN VICENTE" },
  { value: "SANTA", label: "SANTA" },
  { value: "SANTA CATALINA", label: "SANTA CATALINA" },
  { value: "SANTA CRUZ", label: "SANTA CRUZ" },
  { value: "SANTA LUCIA", label: "SANTA LUCIA" },
  { value: "SANTA MARIA", label: "SANTA MARIA" },
  { value: "SANTIAGO", label: "SANTIAGO" },
  { value: "SANTO DOMINGO", label: "SANTO DOMINGO" },
  { value: "SIGAY", label: "SIGAY" },
  { value: "SINAIT", label: "SINAIT" },
  { value: "SUGPON", label: "SUGPON" },
  { value: "SUYO", label: "SUYO" },
  { value: "TAGUDIN", label: "TAGUDIN" },
  { value: "CITY OF VIGAN (Capital)", label: "CITY OF VIGAN (Capital)" },
  { value: "AGOO", label: "AGOO" },
  { value: "ARINGAY", label: "ARINGAY" },
  { value: "BACNOTAN", label: "BACNOTAN" },
  { value: "BAGULIN", label: "BAGULIN" },
  { value: "BALAOAN", label: "BALAOAN" },
  { value: "BANGAR", label: "BANGAR" },
  { value: "BAUANG", label: "BAUANG" },
  { value: "BURGOS", label: "BURGOS" },
  { value: "CABA", label: "CABA" },
  { value: "LUNA", label: "LUNA" },
  { value: "NAGUILIAN", label: "NAGUILIAN" },
  { value: "PUGO", label: "PUGO" },
  { value: "ROSARIO", label: "ROSARIO" },
  {
    value: "CITY OF SAN FERNANDO (Capital)",
    label: "CITY OF SAN FERNANDO (Capital)",
  },
  { value: "SAN GABRIEL", label: "SAN GABRIEL" },
  { value: "SAN JUAN", label: "SAN JUAN" },
  { value: "SANTO TOMAS", label: "SANTO TOMAS" },
  { value: "SANTOL", label: "SANTOL" },
  { value: "SUDIPEN", label: "SUDIPEN" },
  { value: "TUBAO", label: "TUBAO" },
  { value: "AGNO", label: "AGNO" },
  { value: "AGUILAR", label: "AGUILAR" },
  { value: "CITY OF ALAMINOS", label: "CITY OF ALAMINOS" },
  { value: "ALCALA", label: "ALCALA" },
  { value: "ANDA", label: "ANDA" },
  { value: "ASINGAN", label: "ASINGAN" },
  { value: "BALUNGAO", label: "BALUNGAO" },
  { value: "BANI", label: "BANI" },
  { value: "BASISTA", label: "BASISTA" },
  { value: "BAUTISTA", label: "BAUTISTA" },
  { value: "BAYAMBANG", label: "BAYAMBANG" },
  { value: "BINALONAN", label: "BINALONAN" },
  { value: "BINMALEY", label: "BINMALEY" },
  { value: "BOLINAO", label: "BOLINAO" },
  { value: "BUGALLON", label: "BUGALLON" },
  { value: "BURGOS", label: "BURGOS" },
  { value: "CALASIAO", label: "CALASIAO" },
  { value: "DAGUPAN CITY", label: "DAGUPAN CITY" },
  { value: "DASOL", label: "DASOL" },
  { value: "INFANTA", label: "INFANTA" },
  { value: "LABRADOR", label: "LABRADOR" },
  { value: "LINGAYEN (Capital)", label: "LINGAYEN (Capital)" },
  { value: "MABINI", label: "MABINI" },
  { value: "MALASIQUI", label: "MALASIQUI" },
  { value: "MANAOAG", label: "MANAOAG" },
  { value: "MANGALDAN", label: "MANGALDAN" },
  { value: "MANGATAREM", label: "MANGATAREM" },
  { value: "MAPANDAN", label: "MAPANDAN" },
  { value: "NATIVIDAD", label: "NATIVIDAD" },
  { value: "POZORRUBIO", label: "POZORRUBIO" },
  { value: "ROSALES", label: "ROSALES" },
  { value: "SAN CARLOS CITY", label: "SAN CARLOS CITY" },
  { value: "SAN FABIAN", label: "SAN FABIAN" },
  { value: "SAN JACINTO", label: "SAN JACINTO" },
  { value: "SAN MANUEL", label: "SAN MANUEL" },
  { value: "SAN NICOLAS", label: "SAN NICOLAS" },
  { value: "SAN QUINTIN", label: "SAN QUINTIN" },
  { value: "SANTA BARBARA", label: "SANTA BARBARA" },
  { value: "SANTA MARIA", label: "SANTA MARIA" },
  { value: "SANTO TOMAS", label: "SANTO TOMAS" },
  { value: "SISON", label: "SISON" },
  { value: "SUAL", label: "SUAL" },
  { value: "TAYUG", label: "TAYUG" },
  { value: "UMINGAN", label: "UMINGAN" },
  { value: "URBIZTONDO", label: "URBIZTONDO" },
  { value: "CITY OF URDANETA", label: "CITY OF URDANETA" },
  { value: "VILLASIS", label: "VILLASIS" },
  { value: "LAOAC", label: "LAOAC" },
  { value: "BASCO (Capital)", label: "BASCO (Capital)" },
  { value: "ITBAYAT", label: "ITBAYAT" },
  { value: "IVANA", label: "IVANA" },
  { value: "MAHATAO", label: "MAHATAO" },
  { value: "SABTANG", label: "SABTANG" },
  { value: "UYUGAN", label: "UYUGAN" },
  { value: "ABULUG", label: "ABULUG" },
  { value: "ALCALA", label: "ALCALA" },
  { value: "ALLACAPAN", label: "ALLACAPAN" },
  { value: "AMULUNG", label: "AMULUNG" },
  { value: "APARRI", label: "APARRI" },
  { value: "BAGGAO", label: "BAGGAO" },
  { value: "BALLESTEROS", label: "BALLESTEROS" },
  { value: "BUGUEY", label: "BUGUEY" },
  { value: "CALAYAN", label: "CALAYAN" },
  { value: "CAMALANIUGAN", label: "CAMALANIUGAN" },
  { value: "CLAVERIA", label: "CLAVERIA" },
  { value: "ENRILE", label: "ENRILE" },
  { value: "GATTARAN", label: "GATTARAN" },
  { value: "GONZAGA", label: "GONZAGA" },
  { value: "IGUIG", label: "IGUIG" },
  { value: "LAL-LO", label: "LAL-LO" },
  { value: "LASAM", label: "LASAM" },
  { value: "PAMPLONA", label: "PAMPLONA" },
  { value: "PEÑABLANCA", label: "PEÑABLANCA" },
  { value: "PIAT", label: "PIAT" },
  { value: "RIZAL", label: "RIZAL" },
  { value: "SANCHEZ-MIRA", label: "SANCHEZ-MIRA" },
  { value: "SANTA ANA", label: "SANTA ANA" },
  { value: "SANTA PRAXEDES", label: "SANTA PRAXEDES" },
  { value: "SANTA TERESITA", label: "SANTA TERESITA" },
  { value: "SANTO NIÑO (FAIRE)", label: "SANTO NIÑO (FAIRE)" },
  { value: "SOLANA", label: "SOLANA" },
  { value: "TUAO", label: "TUAO" },
  { value: "TUGUEGARAO CITY (Capital)", label: "TUGUEGARAO CITY (Capital)" },
  { value: "ALICIA", label: "ALICIA" },
  { value: "ANGADANAN", label: "ANGADANAN" },
  { value: "AURORA", label: "AURORA" },
  { value: "BENITO SOLIVEN", label: "BENITO SOLIVEN" },
  { value: "BURGOS", label: "BURGOS" },
  { value: "CABAGAN", label: "CABAGAN" },
  { value: "CABATUAN", label: "CABATUAN" },
  { value: "CITY OF CAUAYAN", label: "CITY OF CAUAYAN" },
  { value: "CORDON", label: "CORDON" },
  { value: "DINAPIGUE", label: "DINAPIGUE" },
  { value: "DIVILACAN", label: "DIVILACAN" },
  { value: "ECHAGUE", label: "ECHAGUE" },
  { value: "GAMU", label: "GAMU" },
  { value: "ILAGAN CITY (Capital)", label: "ILAGAN CITY (Capital)" },
  { value: "JONES", label: "JONES" },
  { value: "LUNA", label: "LUNA" },
  { value: "MACONACON", label: "MACONACON" },
  { value: "DELFIN ALBANO (MAGSAYSAY)", label: "DELFIN ALBANO (MAGSAYSAY)" },
  { value: "MALLIG", label: "MALLIG" },
  { value: "NAGUILIAN", label: "NAGUILIAN" },
  { value: "PALANAN", label: "PALANAN" },
  { value: "QUEZON", label: "QUEZON" },
  { value: "QUIRINO", label: "QUIRINO" },
  { value: "RAMON", label: "RAMON" },
  { value: "REINA MERCEDES", label: "REINA MERCEDES" },
  { value: "ROXAS", label: "ROXAS" },
  { value: "SAN AGUSTIN", label: "SAN AGUSTIN" },
  { value: "SAN GUILLERMO", label: "SAN GUILLERMO" },
  { value: "SAN ISIDRO", label: "SAN ISIDRO" },
  { value: "SAN MANUEL", label: "SAN MANUEL" },
  { value: "SAN MARIANO", label: "SAN MARIANO" },
  { value: "SAN MATEO", label: "SAN MATEO" },
  { value: "SAN PABLO", label: "SAN PABLO" },
  { value: "SANTA MARIA", label: "SANTA MARIA" },
  { value: "CITY OF SANTIAGO", label: "CITY OF SANTIAGO" },
  { value: "SANTO TOMAS", label: "SANTO TOMAS" },
  { value: "TUMAUINI", label: "TUMAUINI" },
  { value: "AMBAGUIO", label: "AMBAGUIO" },
  { value: "ARITAO", label: "ARITAO" },
  { value: "BAGABAG", label: "BAGABAG" },
  { value: "BAMBANG", label: "BAMBANG" },
  { value: "BAYOMBONG (Capital)", label: "BAYOMBONG (Capital)" },
  { value: "DIADI", label: "DIADI" },
  { value: "DUPAX DEL NORTE", label: "DUPAX DEL NORTE" },
  { value: "DUPAX DEL SUR", label: "DUPAX DEL SUR" },
  { value: "KASIBU", label: "KASIBU" },
  { value: "KAYAPA", label: "KAYAPA" },
  { value: "QUEZON", label: "QUEZON" },
  { value: "SANTA FE", label: "SANTA FE" },
  { value: "SOLANO", label: "SOLANO" },
  { value: "VILLAVERDE", label: "VILLAVERDE" },
  { value: "ALFONSO CASTANEDA", label: "ALFONSO CASTANEDA" },
  { value: "AGLIPAY", label: "AGLIPAY" },
  { value: "CABARROGUIS (Capital)", label: "CABARROGUIS (Capital)" },
  { value: "DIFFUN", label: "DIFFUN" },
  { value: "MADDELA", label: "MADDELA" },
  { value: "SAGUDAY", label: "SAGUDAY" },
  { value: "NAGTIPUNAN", label: "NAGTIPUNAN" },
  { value: "ABUCAY", label: "ABUCAY" },
  { value: "BAGAC", label: "BAGAC" },
  { value: "CITY OF BALANGA (Capital)", label: "CITY OF BALANGA (Capital)" },
  { value: "DINALUPIHAN", label: "DINALUPIHAN" },
  { value: "HERMOSA", label: "HERMOSA" },
  { value: "LIMAY", label: "LIMAY" },
  { value: "MARIVELES", label: "MARIVELES" },
  { value: "MORONG", label: "MORONG" },
  { value: "ORANI", label: "ORANI" },
  { value: "ORION", label: "ORION" },
  { value: "PILAR", label: "PILAR" },
  { value: "SAMAL", label: "SAMAL" },
  { value: "ANGAT", label: "ANGAT" },
  { value: "BALAGTAS (BIGAA)", label: "BALAGTAS (BIGAA)" },
  { value: "BALIUAG", label: "BALIUAG" },
  { value: "BOCAUE", label: "BOCAUE" },
  { value: "BULACAN", label: "BULACAN" },
  { value: "BUSTOS", label: "BUSTOS" },
  { value: "CALUMPIT", label: "CALUMPIT" },
  { value: "GUIGUINTO", label: "GUIGUINTO" },
  { value: "HAGONOY", label: "HAGONOY" },
  { value: "CITY OF MALOLOS (Capital)", label: "CITY OF MALOLOS (Capital)" },
  { value: "MARILAO", label: "MARILAO" },
  { value: "CITY OF MEYCAUAYAN", label: "CITY OF MEYCAUAYAN" },
  { value: "NORZAGARAY", label: "NORZAGARAY" },
  { value: "OBANDO", label: "OBANDO" },
  { value: "PANDI", label: "PANDI" },
  { value: "PAOMBONG", label: "PAOMBONG" },
  { value: "PLARIDEL", label: "PLARIDEL" },
  { value: "PULILAN", label: "PULILAN" },
  { value: "SAN ILDEFONSO", label: "SAN ILDEFONSO" },
  { value: "CITY OF SAN JOSE DEL MONTE", label: "CITY OF SAN JOSE DEL MONTE" },
  { value: "SAN MIGUEL", label: "SAN MIGUEL" },
  { value: "SAN RAFAEL", label: "SAN RAFAEL" },
  { value: "SANTA MARIA", label: "SANTA MARIA" },
  { value: "DOÑA REMEDIOS TRINIDAD", label: "DOÑA REMEDIOS TRINIDAD" },
  { value: "ALIAGA", label: "ALIAGA" },
  { value: "BONGABON", label: "BONGABON" },
  { value: "CABANATUAN CITY", label: "CABANATUAN CITY" },
  { value: "CABIAO", label: "CABIAO" },
  { value: "CARRANGLAN", label: "CARRANGLAN" },
  { value: "CUYAPO", label: "CUYAPO" },
  {
    value: "GABALDON (BITULOK & SABANI)",
    label: "GABALDON (BITULOK & SABANI)",
  },
  { value: "CITY OF GAPAN", label: "CITY OF GAPAN" },
  { value: "GENERAL MAMERTO NATIVIDAD", label: "GENERAL MAMERTO NATIVIDAD" },
  { value: "GENERAL TINIO (PAPAYA)", label: "GENERAL TINIO (PAPAYA)" },
  { value: "GUIMBA", label: "GUIMBA" },
  { value: "JAEN", label: "JAEN" },
  { value: "LAUR", label: "LAUR" },
  { value: "LICAB", label: "LICAB" },
  { value: "LLANERA", label: "LLANERA" },
  { value: "LUPAO", label: "LUPAO" },
  { value: "SCIENCE CITY OF MUÑOZ", label: "SCIENCE CITY OF MUÑOZ" },
  { value: "NAMPICUAN", label: "NAMPICUAN" },
  { value: "PALAYAN CITY (Capital)", label: "PALAYAN CITY (Capital)" },
  { value: "PANTABANGAN", label: "PANTABANGAN" },
  { value: "PEÑARANDA", label: "PEÑARANDA" },
  { value: "QUEZON", label: "QUEZON" },
  { value: "RIZAL", label: "RIZAL" },
  { value: "SAN ANTONIO", label: "SAN ANTONIO" },
  { value: "SAN ISIDRO", label: "SAN ISIDRO" },
  { value: "SAN JOSE CITY", label: "SAN JOSE CITY" },
  { value: "SAN LEONARDO", label: "SAN LEONARDO" },
  { value: "SANTA ROSA", label: "SANTA ROSA" },
  { value: "SANTO DOMINGO", label: "SANTO DOMINGO" },
  { value: "TALAVERA", label: "TALAVERA" },
  { value: "TALUGTUG", label: "TALUGTUG" },
  { value: "ZARAGOZA", label: "ZARAGOZA" },
  { value: "ANGELES CITY", label: "ANGELES CITY" },
  { value: "APALIT", label: "APALIT" },
  { value: "ARAYAT", label: "ARAYAT" },
  { value: "BACOLOR", label: "BACOLOR" },
  { value: "CANDABA", label: "CANDABA" },
  { value: "FLORIDABLANCA", label: "FLORIDABLANCA" },
  { value: "GUAGUA", label: "GUAGUA" },
  { value: "LUBAO", label: "LUBAO" },
  { value: "MABALACAT CITY", label: "MABALACAT CITY" },
  { value: "MACABEBE", label: "MACABEBE" },
  { value: "MAGALANG", label: "MAGALANG" },
  { value: "MASANTOL", label: "MASANTOL" },
  { value: "MEXICO", label: "MEXICO" },
  { value: "MINALIN", label: "MINALIN" },
  { value: "PORAC", label: "PORAC" },
  {
    value: "CITY OF SAN FERNANDO (Capital)",
    label: "CITY OF SAN FERNANDO (Capital)",
  },
  { value: "SAN LUIS", label: "SAN LUIS" },
  { value: "SAN SIMON", label: "SAN SIMON" },
  { value: "SANTA ANA", label: "SANTA ANA" },
  { value: "SANTA RITA", label: "SANTA RITA" },
  { value: "SANTO TOMAS", label: "SANTO TOMAS" },
  { value: "SASMUAN (Sexmoan)", label: "SASMUAN (Sexmoan)" },
  { value: "ANAO", label: "ANAO" },
  { value: "BAMBAN", label: "BAMBAN" },
  { value: "CAMILING", label: "CAMILING" },
  { value: "CAPAS", label: "CAPAS" },
  { value: "CONCEPCION", label: "CONCEPCION" },
  { value: "GERONA", label: "GERONA" },
  { value: "LA PAZ", label: "LA PAZ" },
  { value: "MAYANTOC", label: "MAYANTOC" },
  { value: "MONCADA", label: "MONCADA" },
  { value: "PANIQUI", label: "PANIQUI" },
  { value: "PURA", label: "PURA" },
  { value: "RAMOS", label: "RAMOS" },
  { value: "SAN CLEMENTE", label: "SAN CLEMENTE" },
  { value: "SAN MANUEL", label: "SAN MANUEL" },
  { value: "SANTA IGNACIA", label: "SANTA IGNACIA" },
  { value: "CITY OF TARLAC (Capital)", label: "CITY OF TARLAC (Capital)" },
  { value: "VICTORIA", label: "VICTORIA" },
  { value: "SAN JOSE", label: "SAN JOSE" },
  { value: "BOTOLAN", label: "BOTOLAN" },
  { value: "CABANGAN", label: "CABANGAN" },
  { value: "CANDELARIA", label: "CANDELARIA" },
  { value: "CASTILLEJOS", label: "CASTILLEJOS" },
  { value: "IBA (Capital)", label: "IBA (Capital)" },
  { value: "MASINLOC", label: "MASINLOC" },
  { value: "OLONGAPO CITY", label: "OLONGAPO CITY" },
  { value: "PALAUIG", label: "PALAUIG" },
  { value: "SAN ANTONIO", label: "SAN ANTONIO" },
  { value: "SAN FELIPE", label: "SAN FELIPE" },
  { value: "SAN MARCELINO", label: "SAN MARCELINO" },
  { value: "SAN NARCISO", label: "SAN NARCISO" },
  { value: "SANTA CRUZ", label: "SANTA CRUZ" },
  { value: "SUBIC", label: "SUBIC" },
  { value: "BALER (Capital)", label: "BALER (Capital)" },
  { value: "CASIGURAN", label: "CASIGURAN" },
  { value: "DILASAG", label: "DILASAG" },
  { value: "DINALUNGAN", label: "DINALUNGAN" },
  { value: "DINGALAN", label: "DINGALAN" },
  { value: "DIPACULAO", label: "DIPACULAO" },
  { value: "MARIA AURORA", label: "MARIA AURORA" },
  { value: "SAN LUIS", label: "SAN LUIS" },
  { value: "AGONCILLO", label: "AGONCILLO" },
  { value: "ALITAGTAG", label: "ALITAGTAG" },
  { value: "BALAYAN", label: "BALAYAN" },
  { value: "BALETE", label: "BALETE" },
  { value: "BATANGAS CITY (Capital)", label: "BATANGAS CITY (Capital)" },
  { value: "BAUAN", label: "BAUAN" },
  { value: "CALACA", label: "CALACA" },
  { value: "CALATAGAN", label: "CALATAGAN" },
  { value: "CUENCA", label: "CUENCA" },
  { value: "IBAAN", label: "IBAAN" },
  { value: "LAUREL", label: "LAUREL" },
  { value: "LEMERY", label: "LEMERY" },
  { value: "LIAN", label: "LIAN" },
  { value: "LIPA CITY", label: "LIPA CITY" },
  { value: "LOBO", label: "LOBO" },
  { value: "MABINI", label: "MABINI" },
  { value: "MALVAR", label: "MALVAR" },
  { value: "MATAASNAKAHOY", label: "MATAASNAKAHOY" },
  { value: "NASUGBU", label: "NASUGBU" },
  { value: "PADRE GARCIA", label: "PADRE GARCIA" },
  { value: "ROSARIO", label: "ROSARIO" },
  { value: "SAN JOSE", label: "SAN JOSE" },
  { value: "SAN JUAN", label: "SAN JUAN" },
  { value: "SAN LUIS", label: "SAN LUIS" },
  { value: "SAN NICOLAS", label: "SAN NICOLAS" },
  { value: "SAN PASCUAL", label: "SAN PASCUAL" },
  { value: "SANTA TERESITA", label: "SANTA TERESITA" },
  { value: "SANTO TOMAS", label: "SANTO TOMAS" },
  { value: "TAAL", label: "TAAL" },
  { value: "TALISAY", label: "TALISAY" },
  { value: "CITY OF TANAUAN", label: "CITY OF TANAUAN" },
  { value: "TAYSAN", label: "TAYSAN" },
  { value: "TINGLOY", label: "TINGLOY" },
  { value: "TUY", label: "TUY" },
  { value: "ALFONSO", label: "ALFONSO" },
  { value: "AMADEO", label: "AMADEO" },
  { value: "BACOOR CITY", label: "BACOOR CITY" },
  { value: "CARMONA", label: "CARMONA" },
  { value: "CAVITE CITY", label: "CAVITE CITY" },
  { value: "CITY OF DASMARIÑAS", label: "CITY OF DASMARIÑAS" },
  { value: "GENERAL EMILIO AGUINALDO", label: "GENERAL EMILIO AGUINALDO" },
  { value: "GENERAL TRIAS", label: "GENERAL TRIAS" },
  { value: "IMUS CITY", label: "IMUS CITY" },
  { value: "INDANG", label: "INDANG" },
  { value: "KAWIT", label: "KAWIT" },
  { value: "MAGALLANES", label: "MAGALLANES" },
  { value: "MARAGONDON", label: "MARAGONDON" },
  { value: "MENDEZ (MENDEZ-NUÑEZ)", label: "MENDEZ (MENDEZ-NUÑEZ)" },
  { value: "NAIC", label: "NAIC" },
  { value: "NOVELETA", label: "NOVELETA" },
  { value: "ROSARIO", label: "ROSARIO" },
  { value: "SILANG", label: "SILANG" },
  { value: "TAGAYTAY CITY", label: "TAGAYTAY CITY" },
  { value: "TANZA", label: "TANZA" },
  { value: "TERNATE", label: "TERNATE" },
  {
    value: "TRECE MARTIRES CITY (Capital)",
    label: "TRECE MARTIRES CITY (Capital)",
  },
  { value: "GEN. MARIANO ALVAREZ", label: "GEN. MARIANO ALVAREZ" },
  { value: "ALAMINOS", label: "ALAMINOS" },
  { value: "BAY", label: "BAY" },
  { value: "CITY OF BIÑAN", label: "CITY OF BIÑAN" },
  { value: "CABUYAO CITY", label: "CABUYAO CITY" },
  { value: "CITY OF CALAMBA", label: "CITY OF CALAMBA" },
  { value: "CALAUAN", label: "CALAUAN" },
  { value: "CAVINTI", label: "CAVINTI" },
  { value: "FAMY", label: "FAMY" },
  { value: "KALAYAAN", label: "KALAYAAN" },
  { value: "LILIW", label: "LILIW" },
  { value: "LOS BAÑOS", label: "LOS BAÑOS" },
  { value: "LUISIANA", label: "LUISIANA" },
  { value: "LUMBAN", label: "LUMBAN" },
  { value: "MABITAC", label: "MABITAC" },
  { value: "MAGDALENA", label: "MAGDALENA" },
  { value: "MAJAYJAY", label: "MAJAYJAY" },
  { value: "NAGCARLAN", label: "NAGCARLAN" },
  { value: "PAETE", label: "PAETE" },
  { value: "PAGSANJAN", label: "PAGSANJAN" },
  { value: "PAKIL", label: "PAKIL" },
  { value: "PANGIL", label: "PANGIL" },
  { value: "PILA", label: "PILA" },
  { value: "RIZAL", label: "RIZAL" },
  { value: "SAN PABLO CITY", label: "SAN PABLO CITY" },
  { value: "CITY OF SAN PEDRO", label: "CITY OF SAN PEDRO" },
  { value: "SANTA CRUZ (Capital)", label: "SANTA CRUZ (Capital)" },
  { value: "SANTA MARIA", label: "SANTA MARIA" },
  { value: "CITY OF SANTA ROSA", label: "CITY OF SANTA ROSA" },
  { value: "SINILOAN", label: "SINILOAN" },
  { value: "VICTORIA", label: "VICTORIA" },
  { value: "AGDANGAN", label: "AGDANGAN" },
  { value: "ALABAT", label: "ALABAT" },
  { value: "ATIMONAN", label: "ATIMONAN" },
  { value: "BUENAVISTA", label: "BUENAVISTA" },
  { value: "BURDEOS", label: "BURDEOS" },
  { value: "CALAUAG", label: "CALAUAG" },
  { value: "CANDELARIA", label: "CANDELARIA" },
  { value: "CATANAUAN", label: "CATANAUAN" },
  { value: "DOLORES", label: "DOLORES" },
  { value: "GENERAL LUNA", label: "GENERAL LUNA" },
  { value: "GENERAL NAKAR", label: "GENERAL NAKAR" },
  { value: "GUINAYANGAN", label: "GUINAYANGAN" },
  { value: "GUMACA", label: "GUMACA" },
  { value: "INFANTA", label: "INFANTA" },
  { value: "JOMALIG", label: "JOMALIG" },
  { value: "LOPEZ", label: "LOPEZ" },
  { value: "LUCBAN", label: "LUCBAN" },
  { value: "LUCENA CITY (Capital)", label: "LUCENA CITY (Capital)" },
  { value: "MACALELON", label: "MACALELON" },
  { value: "MAUBAN", label: "MAUBAN" },
  { value: "MULANAY", label: "MULANAY" },
  { value: "PADRE BURGOS", label: "PADRE BURGOS" },
  { value: "PAGBILAO", label: "PAGBILAO" },
  { value: "PANUKULAN", label: "PANUKULAN" },
  { value: "PATNANUNGAN", label: "PATNANUNGAN" },
  { value: "PEREZ", label: "PEREZ" },
  { value: "PITOGO", label: "PITOGO" },
  { value: "PLARIDEL", label: "PLARIDEL" },
  { value: "POLILLO", label: "POLILLO" },
  { value: "QUEZON", label: "QUEZON" },
  { value: "REAL", label: "REAL" },
  { value: "SAMPALOC", label: "SAMPALOC" },
  { value: "SAN ANDRES", label: "SAN ANDRES" },
  { value: "SAN ANTONIO", label: "SAN ANTONIO" },
  { value: "SAN FRANCISCO (AURORA)", label: "SAN FRANCISCO (AURORA)" },
  { value: "SAN NARCISO", label: "SAN NARCISO" },
  { value: "SARIAYA", label: "SARIAYA" },
  { value: "TAGKAWAYAN", label: "TAGKAWAYAN" },
  { value: "CITY OF TAYABAS", label: "CITY OF TAYABAS" },
  { value: "TIAONG", label: "TIAONG" },
  { value: "UNISAN", label: "UNISAN" },
  { value: "ANGONO", label: "ANGONO" },
  { value: "CITY OF ANTIPOLO", label: "CITY OF ANTIPOLO" },
  { value: "BARAS", label: "BARAS" },
  { value: "BINANGONAN", label: "BINANGONAN" },
  { value: "CAINTA", label: "CAINTA" },
  { value: "CARDONA", label: "CARDONA" },
  { value: "JALA-JALA", label: "JALA-JALA" },
  { value: "RODRIGUEZ (MONTALBAN)", label: "RODRIGUEZ (MONTALBAN)" },
  { value: "MORONG", label: "MORONG" },
  { value: "PILILLA", label: "PILILLA" },
  { value: "SAN MATEO", label: "SAN MATEO" },
  { value: "TANAY", label: "TANAY" },
  { value: "TAYTAY", label: "TAYTAY" },
  { value: "TERESA", label: "TERESA" },
  { value: "BOAC (Capital)", label: "BOAC (Capital)" },
  { value: "BUENAVISTA", label: "BUENAVISTA" },
  { value: "GASAN", label: "GASAN" },
  { value: "MOGPOG", label: "MOGPOG" },
  { value: "SANTA CRUZ", label: "SANTA CRUZ" },
  { value: "TORRIJOS", label: "TORRIJOS" },
  { value: "ABRA DE ILOG", label: "ABRA DE ILOG" },
  { value: "CALINTAAN", label: "CALINTAAN" },
  { value: "LOOC", label: "LOOC" },
  { value: "LUBANG", label: "LUBANG" },
  { value: "MAGSAYSAY", label: "MAGSAYSAY" },
  { value: "MAMBURAO (Capital)", label: "MAMBURAO (Capital)" },
  { value: "PALUAN", label: "PALUAN" },
  { value: "RIZAL", label: "RIZAL" },
  { value: "SABLAYAN", label: "SABLAYAN" },
  { value: "SAN JOSE", label: "SAN JOSE" },
  { value: "SANTA CRUZ", label: "SANTA CRUZ" },
  { value: "BACO", label: "BACO" },
  { value: "BANSUD", label: "BANSUD" },
  { value: "BONGABONG", label: "BONGABONG" },
  { value: "BULALACAO (SAN PEDRO)", label: "BULALACAO (SAN PEDRO)" },
  { value: "CITY OF CALAPAN (Capital)", label: "CITY OF CALAPAN (Capital)" },
  { value: "GLORIA", label: "GLORIA" },
  { value: "MANSALAY", label: "MANSALAY" },
  { value: "NAUJAN", label: "NAUJAN" },
  { value: "PINAMALAYAN", label: "PINAMALAYAN" },
  { value: "POLA", label: "POLA" },
  { value: "PUERTO GALERA", label: "PUERTO GALERA" },
  { value: "ROXAS", label: "ROXAS" },
  { value: "SAN TEODORO", label: "SAN TEODORO" },
  { value: "SOCORRO", label: "SOCORRO" },
  { value: "VICTORIA", label: "VICTORIA" },
  { value: "ABORLAN", label: "ABORLAN" },
  { value: "AGUTAYA", label: "AGUTAYA" },
  { value: "ARACELI", label: "ARACELI" },
  { value: "BALABAC", label: "BALABAC" },
  { value: "BATARAZA", label: "BATARAZA" },
  { value: "BROOKE'S POINT", label: "BROOKE'S POINT" },
  { value: "BUSUANGA", label: "BUSUANGA" },
  { value: "CAGAYANCILLO", label: "CAGAYANCILLO" },
  { value: "CORON", label: "CORON" },
  { value: "CUYO", label: "CUYO" },
  { value: "DUMARAN", label: "DUMARAN" },
  { value: "EL NIDO (BACUIT)", label: "EL NIDO (BACUIT)" },
  { value: "LINAPACAN", label: "LINAPACAN" },
  { value: "MAGSAYSAY", label: "MAGSAYSAY" },
  { value: "NARRA", label: "NARRA" },
  {
    value: "PUERTO PRINCESA CITY (Capital)",
    label: "PUERTO PRINCESA CITY (Capital)",
  },
  { value: "QUEZON", label: "QUEZON" },
  { value: "ROXAS", label: "ROXAS" },
  { value: "SAN VICENTE", label: "SAN VICENTE" },
  { value: "TAYTAY", label: "TAYTAY" },
  { value: "KALAYAAN", label: "KALAYAAN" },
  { value: "CULION", label: "CULION" },
  { value: "RIZAL (MARCOS)", label: "RIZAL (MARCOS)" },
  { value: "SOFRONIO ESPAÑOLA", label: "SOFRONIO ESPAÑOLA" },
  { value: "ALCANTARA", label: "ALCANTARA" },
  { value: "BANTON", label: "BANTON" },
  { value: "CAJIDIOCAN", label: "CAJIDIOCAN" },
  { value: "CALATRAVA", label: "CALATRAVA" },
  { value: "CONCEPCION", label: "CONCEPCION" },
  { value: "CORCUERA", label: "CORCUERA" },
  { value: "LOOC", label: "LOOC" },
  { value: "MAGDIWANG", label: "MAGDIWANG" },
  { value: "ODIONGAN", label: "ODIONGAN" },
  { value: "ROMBLON (Capital)", label: "ROMBLON (Capital)" },
  { value: "SAN AGUSTIN", label: "SAN AGUSTIN" },
  { value: "SAN ANDRES", label: "SAN ANDRES" },
  { value: "SAN FERNANDO", label: "SAN FERNANDO" },
  { value: "SAN JOSE", label: "SAN JOSE" },
  { value: "SANTA FE", label: "SANTA FE" },
  { value: "FERROL", label: "FERROL" },
  { value: "SANTA MARIA (IMELDA)", label: "SANTA MARIA (IMELDA)" },
  { value: "BACACAY", label: "BACACAY" },
  { value: "CAMALIG", label: "CAMALIG" },
  { value: "DARAGA (LOCSIN)", label: "DARAGA (LOCSIN)" },
  { value: "GUINOBATAN", label: "GUINOBATAN" },
  { value: "JOVELLAR", label: "JOVELLAR" },
  { value: "LEGAZPI CITY (Capital)", label: "LEGAZPI CITY (Capital)" },
  { value: "LIBON", label: "LIBON" },
  { value: "CITY OF LIGAO", label: "CITY OF LIGAO" },
  { value: "MALILIPOT", label: "MALILIPOT" },
  { value: "MALINAO", label: "MALINAO" },
  { value: "MANITO", label: "MANITO" },
  { value: "OAS", label: "OAS" },
  { value: "PIO DURAN", label: "PIO DURAN" },
  { value: "POLANGUI", label: "POLANGUI" },
  { value: "RAPU-RAPU", label: "RAPU-RAPU" },
  { value: "SANTO DOMINGO (LIBOG)", label: "SANTO DOMINGO (LIBOG)" },
  { value: "CITY OF TABACO", label: "CITY OF TABACO" },
  { value: "TIWI", label: "TIWI" },
  { value: "BASUD", label: "BASUD" },
  { value: "CAPALONGA", label: "CAPALONGA" },
  { value: "DAET (Capital)", label: "DAET (Capital)" },
  { value: "SAN LORENZO RUIZ (IMELDA)", label: "SAN LORENZO RUIZ (IMELDA)" },
  { value: "JOSE PANGANIBAN", label: "JOSE PANGANIBAN" },
  { value: "LABO", label: "LABO" },
  { value: "MERCEDES", label: "MERCEDES" },
  { value: "PARACALE", label: "PARACALE" },
  { value: "SAN VICENTE", label: "SAN VICENTE" },
  { value: "SANTA ELENA", label: "SANTA ELENA" },
  { value: "TALISAY", label: "TALISAY" },
  { value: "VINZONS", label: "VINZONS" },
  { value: "BAAO", label: "BAAO" },
  { value: "BALATAN", label: "BALATAN" },
  { value: "BATO", label: "BATO" },
  { value: "BOMBON", label: "BOMBON" },
  { value: "BUHI", label: "BUHI" },
  { value: "BULA", label: "BULA" },
  { value: "CABUSAO", label: "CABUSAO" },
  { value: "CALABANGA", label: "CALABANGA" },
  { value: "CAMALIGAN", label: "CAMALIGAN" },
  { value: "CANAMAN", label: "CANAMAN" },
  { value: "CARAMOAN", label: "CARAMOAN" },
  { value: "DEL GALLEGO", label: "DEL GALLEGO" },
  { value: "GAINZA", label: "GAINZA" },
  { value: "GARCHITORENA", label: "GARCHITORENA" },
  { value: "GOA", label: "GOA" },
  { value: "IRIGA CITY", label: "IRIGA CITY" },
  { value: "LAGONOY", label: "LAGONOY" },
  { value: "LIBMANAN", label: "LIBMANAN" },
  { value: "LUPI", label: "LUPI" },
  { value: "MAGARAO", label: "MAGARAO" },
  { value: "MILAOR", label: "MILAOR" },
  { value: "MINALABAC", label: "MINALABAC" },
  { value: "NABUA", label: "NABUA" },
  { value: "NAGA CITY", label: "NAGA CITY" },
  { value: "OCAMPO", label: "OCAMPO" },
  { value: "PAMPLONA", label: "PAMPLONA" },
  { value: "PASACAO", label: "PASACAO" },
  { value: "PILI (Capital)", label: "PILI (Capital)" },
  { value: "PRESENTACION (PARUBCAN)", label: "PRESENTACION (PARUBCAN)" },
  { value: "RAGAY", label: "RAGAY" },
  { value: "SAGÑAY", label: "SAGÑAY" },
  { value: "SAN FERNANDO", label: "SAN FERNANDO" },
  { value: "SAN JOSE", label: "SAN JOSE" },
  { value: "SIPOCOT", label: "SIPOCOT" },
  { value: "SIRUMA", label: "SIRUMA" },
  { value: "TIGAON", label: "TIGAON" },
  { value: "TINAMBAC", label: "TINAMBAC" },
  { value: "BAGAMANOC", label: "BAGAMANOC" },
  { value: "BARAS", label: "BARAS" },
  { value: "BATO", label: "BATO" },
  { value: "CARAMORAN", label: "CARAMORAN" },
  { value: "GIGMOTO", label: "GIGMOTO" },
  { value: "PANDAN", label: "PANDAN" },
  { value: "PANGANIBAN (PAYO)", label: "PANGANIBAN (PAYO)" },
  { value: "SAN ANDRES (CALOLBON)", label: "SAN ANDRES (CALOLBON)" },
  { value: "SAN MIGUEL", label: "SAN MIGUEL" },
  { value: "VIGA", label: "VIGA" },
  { value: "VIRAC (Capital)", label: "VIRAC (Capital)" },
  { value: "AROROY", label: "AROROY" },
  { value: "BALENO", label: "BALENO" },
  { value: "BALUD", label: "BALUD" },
  { value: "BATUAN", label: "BATUAN" },
  { value: "CATAINGAN", label: "CATAINGAN" },
  { value: "CAWAYAN", label: "CAWAYAN" },
  { value: "CLAVERIA", label: "CLAVERIA" },
  { value: "DIMASALANG", label: "DIMASALANG" },
  { value: "ESPERANZA", label: "ESPERANZA" },
  { value: "MANDAON", label: "MANDAON" },
  { value: "CITY OF MASBATE (Capital)", label: "CITY OF MASBATE (Capital)" },
  { value: "MILAGROS", label: "MILAGROS" },
  { value: "MOBO", label: "MOBO" },
  { value: "MONREAL", label: "MONREAL" },
  { value: "PALANAS", label: "PALANAS" },
  { value: "PIO V. CORPUZ (LIMBUHAN)", label: "PIO V. CORPUZ (LIMBUHAN)" },
  { value: "PLACER", label: "PLACER" },
  { value: "SAN FERNANDO", label: "SAN FERNANDO" },
  { value: "SAN JACINTO", label: "SAN JACINTO" },
  { value: "SAN PASCUAL", label: "SAN PASCUAL" },
  { value: "USON", label: "USON" },
  { value: "BARCELONA", label: "BARCELONA" },
  { value: "BULAN", label: "BULAN" },
  { value: "BULUSAN", label: "BULUSAN" },
  { value: "CASIGURAN", label: "CASIGURAN" },
  { value: "CASTILLA", label: "CASTILLA" },
  { value: "DONSOL", label: "DONSOL" },
  { value: "GUBAT", label: "GUBAT" },
  { value: "IROSIN", label: "IROSIN" },
  { value: "JUBAN", label: "JUBAN" },
  { value: "MAGALLANES", label: "MAGALLANES" },
  { value: "MATNOG", label: "MATNOG" },
  { value: "PILAR", label: "PILAR" },
  { value: "PRIETO DIAZ", label: "PRIETO DIAZ" },
  { value: "SANTA MAGDALENA", label: "SANTA MAGDALENA" },
  { value: "CITY OF SORSOGON (Capital)", label: "CITY OF SORSOGON (Capital)" },
  { value: "ALTAVAS", label: "ALTAVAS" },
  { value: "BALETE", label: "BALETE" },
  { value: "BANGA", label: "BANGA" },
  { value: "BATAN", label: "BATAN" },
  { value: "BURUANGA", label: "BURUANGA" },
  { value: "IBAJAY", label: "IBAJAY" },
  { value: "KALIBO (Capital)", label: "KALIBO (Capital)" },
  { value: "LEZO", label: "LEZO" },
  { value: "LIBACAO", label: "LIBACAO" },
  { value: "MADALAG", label: "MADALAG" },
  { value: "MAKATO", label: "MAKATO" },
  { value: "MALAY", label: "MALAY" },
  { value: "MALINAO", label: "MALINAO" },
  { value: "NABAS", label: "NABAS" },
  { value: "NEW WASHINGTON", label: "NEW WASHINGTON" },
  { value: "NUMANCIA", label: "NUMANCIA" },
  { value: "TANGALAN", label: "TANGALAN" },
  { value: "ANINI-Y", label: "ANINI-Y" },
  { value: "BARBAZA", label: "BARBAZA" },
  { value: "BELISON", label: "BELISON" },
  { value: "BUGASONG", label: "BUGASONG" },
  { value: "CALUYA", label: "CALUYA" },
  { value: "CULASI", label: "CULASI" },
  { value: "TOBIAS FORNIER (DAO)", label: "TOBIAS FORNIER (DAO)" },
  { value: "HAMTIC", label: "HAMTIC" },
  { value: "LAUA-AN", label: "LAUA-AN" },
  { value: "LIBERTAD", label: "LIBERTAD" },
  { value: "PANDAN", label: "PANDAN" },
  { value: "PATNONGON", label: "PATNONGON" },
  { value: "SAN JOSE (Capital)", label: "SAN JOSE (Capital)" },
  { value: "SAN REMIGIO", label: "SAN REMIGIO" },
  { value: "SEBASTE", label: "SEBASTE" },
  { value: "SIBALOM", label: "SIBALOM" },
  { value: "TIBIAO", label: "TIBIAO" },
  { value: "VALDERRAMA", label: "VALDERRAMA" },
  { value: "CUARTERO", label: "CUARTERO" },
  { value: "DAO", label: "DAO" },
  { value: "DUMALAG", label: "DUMALAG" },
  { value: "DUMARAO", label: "DUMARAO" },
  { value: "IVISAN", label: "IVISAN" },
  { value: "JAMINDAN", label: "JAMINDAN" },
  { value: "MA-AYON", label: "MA-AYON" },
  { value: "MAMBUSAO", label: "MAMBUSAO" },
  { value: "PANAY", label: "PANAY" },
  { value: "PANITAN", label: "PANITAN" },
  { value: "PILAR", label: "PILAR" },
  { value: "PONTEVEDRA", label: "PONTEVEDRA" },
  { value: "PRESIDENT ROXAS", label: "PRESIDENT ROXAS" },
  { value: "ROXAS CITY (Capital)", label: "ROXAS CITY (Capital)" },
  { value: "SAPI-AN", label: "SAPI-AN" },
  { value: "SIGMA", label: "SIGMA" },
  { value: "TAPAZ", label: "TAPAZ" },
  { value: "AJUY", label: "AJUY" },
  { value: "ALIMODIAN", label: "ALIMODIAN" },
  { value: "ANILAO", label: "ANILAO" },
  { value: "BADIANGAN", label: "BADIANGAN" },
  { value: "BALASAN", label: "BALASAN" },
  { value: "BANATE", label: "BANATE" },
  { value: "BAROTAC NUEVO", label: "BAROTAC NUEVO" },
  { value: "BAROTAC VIEJO", label: "BAROTAC VIEJO" },
  { value: "BATAD", label: "BATAD" },
  { value: "BINGAWAN", label: "BINGAWAN" },
  { value: "CABATUAN", label: "CABATUAN" },
  { value: "CALINOG", label: "CALINOG" },
  { value: "CARLES", label: "CARLES" },
  { value: "CONCEPCION", label: "CONCEPCION" },
  { value: "DINGLE", label: "DINGLE" },
  { value: "DUEÑAS", label: "DUEÑAS" },
  { value: "DUMANGAS", label: "DUMANGAS" },
  { value: "ESTANCIA", label: "ESTANCIA" },
  { value: "GUIMBAL", label: "GUIMBAL" },
  { value: "IGBARAS", label: "IGBARAS" },
  { value: "ILOILO CITY (Capital)", label: "ILOILO CITY (Capital)" },
  { value: "JANIUAY", label: "JANIUAY" },
  { value: "LAMBUNAO", label: "LAMBUNAO" },
  { value: "LEGANES", label: "LEGANES" },
  { value: "LEMERY", label: "LEMERY" },
  { value: "LEON", label: "LEON" },
  { value: "MAASIN", label: "MAASIN" },
  { value: "MIAGAO", label: "MIAGAO" },
  { value: "MINA", label: "MINA" },
  { value: "NEW LUCENA", label: "NEW LUCENA" },
  { value: "OTON", label: "OTON" },
  { value: "CITY OF PASSI", label: "CITY OF PASSI" },
  { value: "PAVIA", label: "PAVIA" },
  { value: "POTOTAN", label: "POTOTAN" },
  { value: "SAN DIONISIO", label: "SAN DIONISIO" },
  { value: "SAN ENRIQUE", label: "SAN ENRIQUE" },
  { value: "SAN JOAQUIN", label: "SAN JOAQUIN" },
  { value: "SAN MIGUEL", label: "SAN MIGUEL" },
  { value: "SAN RAFAEL", label: "SAN RAFAEL" },
  { value: "SANTA BARBARA", label: "SANTA BARBARA" },
  { value: "SARA", label: "SARA" },
  { value: "TIGBAUAN", label: "TIGBAUAN" },
  { value: "TUBUNGAN", label: "TUBUNGAN" },
  { value: "ZARRAGA", label: "ZARRAGA" },
  { value: "BACOLOD CITY (Capital)", label: "BACOLOD CITY (Capital)" },
  { value: "BAGO CITY", label: "BAGO CITY" },
  { value: "BINALBAGAN", label: "BINALBAGAN" },
  { value: "CADIZ CITY", label: "CADIZ CITY" },
  { value: "CALATRAVA", label: "CALATRAVA" },
  { value: "CANDONI", label: "CANDONI" },
  { value: "CAUAYAN", label: "CAUAYAN" },
  {
    value: "ENRIQUE B. MAGALONA (SARAVIA)",
    label: "ENRIQUE B. MAGALONA (SARAVIA)",
  },
  { value: "CITY OF ESCALANTE", label: "CITY OF ESCALANTE" },
  { value: "CITY OF HIMAMAYLAN", label: "CITY OF HIMAMAYLAN" },
  { value: "HINIGARAN", label: "HINIGARAN" },
  { value: "HINOBA-AN (ASIA)", label: "HINOBA-AN (ASIA)" },
  { value: "ILOG", label: "ILOG" },
  { value: "ISABELA", label: "ISABELA" },
  { value: "CITY OF KABANKALAN", label: "CITY OF KABANKALAN" },
  { value: "LA CARLOTA CITY", label: "LA CARLOTA CITY" },
  { value: "LA CASTELLANA", label: "LA CASTELLANA" },
  { value: "MANAPLA", label: "MANAPLA" },
  { value: "MOISES PADILLA (MAGALLON)", label: "MOISES PADILLA (MAGALLON)" },
  { value: "MURCIA", label: "MURCIA" },
  { value: "PONTEVEDRA", label: "PONTEVEDRA" },
  { value: "PULUPANDAN", label: "PULUPANDAN" },
  { value: "SAGAY CITY", label: "SAGAY CITY" },
  { value: "SAN CARLOS CITY", label: "SAN CARLOS CITY" },
  { value: "SAN ENRIQUE", label: "SAN ENRIQUE" },
  { value: "SILAY CITY", label: "SILAY CITY" },
  { value: "CITY OF SIPALAY", label: "CITY OF SIPALAY" },
  { value: "CITY OF TALISAY", label: "CITY OF TALISAY" },
  { value: "TOBOSO", label: "TOBOSO" },
  { value: "VALLADOLID", label: "VALLADOLID" },
  { value: "CITY OF VICTORIAS", label: "CITY OF VICTORIAS" },
  { value: "SALVADOR BENEDICTO", label: "SALVADOR BENEDICTO" },
  { value: "BUENAVISTA", label: "BUENAVISTA" },
  { value: "JORDAN (Capital)", label: "JORDAN (Capital)" },
  { value: "NUEVA VALENCIA", label: "NUEVA VALENCIA" },
  { value: "SAN LORENZO", label: "SAN LORENZO" },
  { value: "SIBUNAG", label: "SIBUNAG" },
  { value: "ALBURQUERQUE", label: "ALBURQUERQUE" },
  { value: "ALICIA", label: "ALICIA" },
  { value: "ANDA", label: "ANDA" },
  { value: "ANTEQUERA", label: "ANTEQUERA" },
  { value: "BACLAYON", label: "BACLAYON" },
  { value: "BALILIHAN", label: "BALILIHAN" },
  { value: "BATUAN", label: "BATUAN" },
  { value: "BILAR", label: "BILAR" },
  { value: "BUENAVISTA", label: "BUENAVISTA" },
  { value: "CALAPE", label: "CALAPE" },
  { value: "CANDIJAY", label: "CANDIJAY" },
  { value: "CARMEN", label: "CARMEN" },
  { value: "CATIGBIAN", label: "CATIGBIAN" },
  { value: "CLARIN", label: "CLARIN" },
  { value: "CORELLA", label: "CORELLA" },
  { value: "CORTES", label: "CORTES" },
  { value: "DAGOHOY", label: "DAGOHOY" },
  { value: "DANAO", label: "DANAO" },
  { value: "DAUIS", label: "DAUIS" },
  { value: "DIMIAO", label: "DIMIAO" },
  { value: "DUERO", label: "DUERO" },
  { value: "GARCIA HERNANDEZ", label: "GARCIA HERNANDEZ" },
  { value: "GUINDULMAN", label: "GUINDULMAN" },
  { value: "INABANGA", label: "INABANGA" },
  { value: "JAGNA", label: "JAGNA" },
  { value: "JETAFE", label: "JETAFE" },
  { value: "LILA", label: "LILA" },
  { value: "LOAY", label: "LOAY" },
  { value: "LOBOC", label: "LOBOC" },
  { value: "LOON", label: "LOON" },
  { value: "MABINI", label: "MABINI" },
  { value: "MARIBOJOC", label: "MARIBOJOC" },
  { value: "PANGLAO", label: "PANGLAO" },
  { value: "PILAR", label: "PILAR" },
  {
    value: "PRES. CARLOS P. GARCIA (PITOGO)",
    label: "PRES. CARLOS P. GARCIA (PITOGO)",
  },
  { value: "SAGBAYAN (BORJA)", label: "SAGBAYAN (BORJA)" },
  { value: "SAN ISIDRO", label: "SAN ISIDRO" },
  { value: "SAN MIGUEL", label: "SAN MIGUEL" },
  { value: "SEVILLA", label: "SEVILLA" },
  { value: "SIERRA BULLONES", label: "SIERRA BULLONES" },
  { value: "SIKATUNA", label: "SIKATUNA" },
  { value: "TAGBILARAN CITY (Capital)", label: "TAGBILARAN CITY (Capital)" },
  { value: "TALIBON", label: "TALIBON" },
  { value: "TRINIDAD", label: "TRINIDAD" },
  { value: "TUBIGON", label: "TUBIGON" },
  { value: "UBAY", label: "UBAY" },
  { value: "VALENCIA", label: "VALENCIA" },
  { value: "BIEN UNIDO", label: "BIEN UNIDO" },
  { value: "ALCANTARA", label: "ALCANTARA" },
  { value: "ALCOY", label: "ALCOY" },
  { value: "ALEGRIA", label: "ALEGRIA" },
  { value: "ALOGUINSAN", label: "ALOGUINSAN" },
  { value: "ARGAO", label: "ARGAO" },
  { value: "ASTURIAS", label: "ASTURIAS" },
  { value: "BADIAN", label: "BADIAN" },
  { value: "BALAMBAN", label: "BALAMBAN" },
  { value: "BANTAYAN", label: "BANTAYAN" },
  { value: "BARILI", label: "BARILI" },
  { value: "CITY OF BOGO", label: "CITY OF BOGO" },
  { value: "BOLJOON", label: "BOLJOON" },
  { value: "BORBON", label: "BORBON" },
  { value: "CITY OF CARCAR", label: "CITY OF CARCAR" },
  { value: "CARMEN", label: "CARMEN" },
  { value: "CATMON", label: "CATMON" },
  { value: "CEBU CITY (Capital)", label: "CEBU CITY (Capital)" },
  { value: "COMPOSTELA", label: "COMPOSTELA" },
  { value: "CONSOLACION", label: "CONSOLACION" },
  { value: "CORDOVA", label: "CORDOVA" },
  { value: "DAANBANTAYAN", label: "DAANBANTAYAN" },
  { value: "DALAGUETE", label: "DALAGUETE" },
  { value: "DANAO CITY", label: "DANAO CITY" },
  { value: "DUMANJUG", label: "DUMANJUG" },
  { value: "GINATILAN", label: "GINATILAN" },
  { value: "LAPU-LAPU CITY (OPON)", label: "LAPU-LAPU CITY (OPON)" },
  { value: "LILOAN", label: "LILOAN" },
  { value: "MADRIDEJOS", label: "MADRIDEJOS" },
  { value: "MALABUYOC", label: "MALABUYOC" },
  { value: "MANDAUE CITY", label: "MANDAUE CITY" },
  { value: "MEDELLIN", label: "MEDELLIN" },
  { value: "MINGLANILLA", label: "MINGLANILLA" },
  { value: "MOALBOAL", label: "MOALBOAL" },
  { value: "CITY OF NAGA", label: "CITY OF NAGA" },
  { value: "OSLOB", label: "OSLOB" },
  { value: "PILAR", label: "PILAR" },
  { value: "PINAMUNGAHAN", label: "PINAMUNGAHAN" },
  { value: "PORO", label: "PORO" },
  { value: "RONDA", label: "RONDA" },
  { value: "SAMBOAN", label: "SAMBOAN" },
  { value: "SAN FERNANDO", label: "SAN FERNANDO" },
  { value: "SAN FRANCISCO", label: "SAN FRANCISCO" },
  { value: "SAN REMIGIO", label: "SAN REMIGIO" },
  { value: "SANTA FE", label: "SANTA FE" },
  { value: "SANTANDER", label: "SANTANDER" },
  { value: "SIBONGA", label: "SIBONGA" },
  { value: "SOGOD", label: "SOGOD" },
  { value: "TABOGON", label: "TABOGON" },
  { value: "TABUELAN", label: "TABUELAN" },
  { value: "CITY OF TALISAY", label: "CITY OF TALISAY" },
  { value: "TOLEDO CITY", label: "TOLEDO CITY" },
  { value: "TUBURAN", label: "TUBURAN" },
  { value: "TUDELA", label: "TUDELA" },
  { value: "AMLAN (AYUQUITAN)", label: "AMLAN (AYUQUITAN)" },
  { value: "AYUNGON", label: "AYUNGON" },
  { value: "BACONG", label: "BACONG" },
  { value: "BAIS CITY", label: "BAIS CITY" },
  { value: "BASAY", label: "BASAY" },
  { value: "CITY OF BAYAWAN (TULONG)", label: "CITY OF BAYAWAN (TULONG)" },
  { value: "BINDOY (PAYABON)", label: "BINDOY (PAYABON)" },
  { value: "CANLAON CITY", label: "CANLAON CITY" },
  { value: "DAUIN", label: "DAUIN" },
  { value: "DUMAGUETE CITY (Capital)", label: "DUMAGUETE CITY (Capital)" },
  { value: "CITY OF GUIHULNGAN", label: "CITY OF GUIHULNGAN" },
  { value: "JIMALALUD", label: "JIMALALUD" },
  { value: "LA LIBERTAD", label: "LA LIBERTAD" },
  { value: "MABINAY", label: "MABINAY" },
  { value: "MANJUYOD", label: "MANJUYOD" },
  { value: "PAMPLONA", label: "PAMPLONA" },
  { value: "SAN JOSE", label: "SAN JOSE" },
  { value: "SANTA CATALINA", label: "SANTA CATALINA" },
  { value: "SIATON", label: "SIATON" },
  { value: "SIBULAN", label: "SIBULAN" },
  { value: "CITY OF TANJAY", label: "CITY OF TANJAY" },
  { value: "TAYASAN", label: "TAYASAN" },
  { value: "VALENCIA (LUZURRIAGA)", label: "VALENCIA (LUZURRIAGA)" },
  { value: "VALLEHERMOSO", label: "VALLEHERMOSO" },
  { value: "ZAMBOANGUITA", label: "ZAMBOANGUITA" },
  { value: "ENRIQUE VILLANUEVA", label: "ENRIQUE VILLANUEVA" },
  { value: "LARENA", label: "LARENA" },
  { value: "LAZI", label: "LAZI" },
  { value: "MARIA", label: "MARIA" },
  { value: "SAN JUAN", label: "SAN JUAN" },
  { value: "SIQUIJOR (Capital)", label: "SIQUIJOR (Capital)" },
  { value: "ARTECHE", label: "ARTECHE" },
  { value: "BALANGIGA", label: "BALANGIGA" },
  { value: "BALANGKAYAN", label: "BALANGKAYAN" },
  { value: "CITY OF BORONGAN (Capital)", label: "CITY OF BORONGAN (Capital)" },
  { value: "CAN-AVID", label: "CAN-AVID" },
  { value: "DOLORES", label: "DOLORES" },
  { value: "GENERAL MACARTHUR", label: "GENERAL MACARTHUR" },
  { value: "GIPORLOS", label: "GIPORLOS" },
  { value: "GUIUAN", label: "GUIUAN" },
  { value: "HERNANI", label: "HERNANI" },
  { value: "JIPAPAD", label: "JIPAPAD" },
  { value: "LAWAAN", label: "LAWAAN" },
  { value: "LLORENTE", label: "LLORENTE" },
  { value: "MASLOG", label: "MASLOG" },
  { value: "MAYDOLONG", label: "MAYDOLONG" },
  { value: "MERCEDES", label: "MERCEDES" },
  { value: "ORAS", label: "ORAS" },
  { value: "QUINAPONDAN", label: "QUINAPONDAN" },
  { value: "SALCEDO", label: "SALCEDO" },
  { value: "SAN JULIAN", label: "SAN JULIAN" },
  { value: "SAN POLICARPO", label: "SAN POLICARPO" },
  { value: "SULAT", label: "SULAT" },
  { value: "TAFT", label: "TAFT" },
  { value: "ABUYOG", label: "ABUYOG" },
  { value: "ALANGALANG", label: "ALANGALANG" },
  { value: "ALBUERA", label: "ALBUERA" },
  { value: "BABATNGON", label: "BABATNGON" },
  { value: "BARUGO", label: "BARUGO" },
  { value: "BATO", label: "BATO" },
  { value: "CITY OF BAYBAY", label: "CITY OF BAYBAY" },
  { value: "BURAUEN", label: "BURAUEN" },
  { value: "CALUBIAN", label: "CALUBIAN" },
  { value: "CAPOOCAN", label: "CAPOOCAN" },
  { value: "CARIGARA", label: "CARIGARA" },
  { value: "DAGAMI", label: "DAGAMI" },
  { value: "DULAG", label: "DULAG" },
  { value: "HILONGOS", label: "HILONGOS" },
  { value: "HINDANG", label: "HINDANG" },
  { value: "INOPACAN", label: "INOPACAN" },
  { value: "ISABEL", label: "ISABEL" },
  { value: "JARO", label: "JARO" },
  { value: "JAVIER (BUGHO)", label: "JAVIER (BUGHO)" },
  { value: "JULITA", label: "JULITA" },
  { value: "KANANGA", label: "KANANGA" },
  { value: "LA PAZ", label: "LA PAZ" },
  { value: "LEYTE", label: "LEYTE" },
  { value: "MACARTHUR", label: "MACARTHUR" },
  { value: "MAHAPLAG", label: "MAHAPLAG" },
  { value: "MATAG-OB", label: "MATAG-OB" },
  { value: "MATALOM", label: "MATALOM" },
  { value: "MAYORGA", label: "MAYORGA" },
  { value: "MERIDA", label: "MERIDA" },
  { value: "ORMOC CITY", label: "ORMOC CITY" },
  { value: "PALO", label: "PALO" },
  { value: "PALOMPON", label: "PALOMPON" },
  { value: "PASTRANA", label: "PASTRANA" },
  { value: "SAN ISIDRO", label: "SAN ISIDRO" },
  { value: "SAN MIGUEL", label: "SAN MIGUEL" },
  { value: "SANTA FE", label: "SANTA FE" },
  { value: "TABANGO", label: "TABANGO" },
  { value: "TABONTABON", label: "TABONTABON" },
  { value: "TACLOBAN CITY (Capital)", label: "TACLOBAN CITY (Capital)" },
  { value: "TANAUAN", label: "TANAUAN" },
  { value: "TOLOSA", label: "TOLOSA" },
  { value: "TUNGA", label: "TUNGA" },
  { value: "VILLABA", label: "VILLABA" },
  { value: "ALLEN", label: "ALLEN" },
  { value: "BIRI", label: "BIRI" },
  { value: "BOBON", label: "BOBON" },
  { value: "CAPUL", label: "CAPUL" },
  { value: "CATARMAN (Capital)", label: "CATARMAN (Capital)" },
  { value: "CATUBIG", label: "CATUBIG" },
  { value: "GAMAY", label: "GAMAY" },
  { value: "LAOANG", label: "LAOANG" },
  { value: "LAPINIG", label: "LAPINIG" },
  { value: "LAS NAVAS", label: "LAS NAVAS" },
  { value: "LAVEZARES", label: "LAVEZARES" },
  { value: "MAPANAS", label: "MAPANAS" },
  { value: "MONDRAGON", label: "MONDRAGON" },
  { value: "PALAPAG", label: "PALAPAG" },
  { value: "PAMBUJAN", label: "PAMBUJAN" },
  { value: "ROSARIO", label: "ROSARIO" },
  { value: "SAN ANTONIO", label: "SAN ANTONIO" },
  { value: "SAN ISIDRO", label: "SAN ISIDRO" },
  { value: "SAN JOSE", label: "SAN JOSE" },
  { value: "SAN ROQUE", label: "SAN ROQUE" },
  { value: "SAN VICENTE", label: "SAN VICENTE" },
  { value: "SILVINO LOBOS", label: "SILVINO LOBOS" },
  { value: "VICTORIA", label: "VICTORIA" },
  { value: "LOPE DE VEGA", label: "LOPE DE VEGA" },
  { value: "ALMAGRO", label: "ALMAGRO" },
  { value: "BASEY", label: "BASEY" },
  { value: "CALBAYOG CITY", label: "CALBAYOG CITY" },
  { value: "CALBIGA", label: "CALBIGA" },
  {
    value: "CITY OF CATBALOGAN (Capital)",
    label: "CITY OF CATBALOGAN (Capital)",
  },
  { value: "DARAM", label: "DARAM" },
  { value: "GANDARA", label: "GANDARA" },
  { value: "HINABANGAN", label: "HINABANGAN" },
  { value: "JIABONG", label: "JIABONG" },
  { value: "MARABUT", label: "MARABUT" },
  { value: "MATUGUINAO", label: "MATUGUINAO" },
  { value: "MOTIONG", label: "MOTIONG" },
  { value: "PINABACDAO", label: "PINABACDAO" },
  { value: "SAN JOSE DE BUAN", label: "SAN JOSE DE BUAN" },
  { value: "SAN SEBASTIAN", label: "SAN SEBASTIAN" },
  { value: "SANTA MARGARITA", label: "SANTA MARGARITA" },
  { value: "SANTA RITA", label: "SANTA RITA" },
  { value: "SANTO NIÑO", label: "SANTO NIÑO" },
  { value: "TALALORA", label: "TALALORA" },
  { value: "TARANGNAN", label: "TARANGNAN" },
  { value: "VILLAREAL", label: "VILLAREAL" },
  { value: "PARANAS (WRIGHT)", label: "PARANAS (WRIGHT)" },
  { value: "ZUMARRAGA", label: "ZUMARRAGA" },
  { value: "TAGAPUL-AN", label: "TAGAPUL-AN" },
  { value: "SAN JORGE", label: "SAN JORGE" },
  { value: "PAGSANGHAN", label: "PAGSANGHAN" },
  { value: "ANAHAWAN", label: "ANAHAWAN" },
  { value: "BONTOC", label: "BONTOC" },
  { value: "HINUNANGAN", label: "HINUNANGAN" },
  { value: "HINUNDAYAN", label: "HINUNDAYAN" },
  { value: "LIBAGON", label: "LIBAGON" },
  { value: "LILOAN", label: "LILOAN" },
  { value: "CITY OF MAASIN (Capital)", label: "CITY OF MAASIN (Capital)" },
  { value: "MACROHON", label: "MACROHON" },
  { value: "MALITBOG", label: "MALITBOG" },
  { value: "PADRE BURGOS", label: "PADRE BURGOS" },
  { value: "PINTUYAN", label: "PINTUYAN" },
  { value: "SAINT BERNARD", label: "SAINT BERNARD" },
  { value: "SAN FRANCISCO", label: "SAN FRANCISCO" },
  { value: "SAN JUAN (CABALIAN)", label: "SAN JUAN (CABALIAN)" },
  { value: "SAN RICARDO", label: "SAN RICARDO" },
  { value: "SILAGO", label: "SILAGO" },
  { value: "SOGOD", label: "SOGOD" },
  { value: "TOMAS OPPUS", label: "TOMAS OPPUS" },
  { value: "LIMASAWA", label: "LIMASAWA" },
  { value: "ALMERIA", label: "ALMERIA" },
  { value: "BILIRAN", label: "BILIRAN" },
  { value: "CABUCGAYAN", label: "CABUCGAYAN" },
  { value: "CAIBIRAN", label: "CAIBIRAN" },
  { value: "CULABA", label: "CULABA" },
  { value: "KAWAYAN", label: "KAWAYAN" },
  { value: "MARIPIPI", label: "MARIPIPI" },
  { value: "NAVAL (Capital)", label: "NAVAL (Capital)" },
  { value: "DAPITAN CITY", label: "DAPITAN CITY" },
  { value: "DIPOLOG CITY (Capital)", label: "DIPOLOG CITY (Capital)" },
  { value: "KATIPUNAN", label: "KATIPUNAN" },
  { value: "LA LIBERTAD", label: "LA LIBERTAD" },
  { value: "LABASON", label: "LABASON" },
  { value: "LILOY", label: "LILOY" },
  { value: "MANUKAN", label: "MANUKAN" },
  { value: "MUTIA", label: "MUTIA" },
  { value: "PIÑAN (NEW PIÑAN)", label: "PIÑAN (NEW PIÑAN)" },
  { value: "POLANCO", label: "POLANCO" },
  { value: "PRES. MANUEL A. ROXAS", label: "PRES. MANUEL A. ROXAS" },
  { value: "RIZAL", label: "RIZAL" },
  { value: "SALUG", label: "SALUG" },
  { value: "SERGIO OSMEÑA SR.", label: "SERGIO OSMEÑA SR." },
  { value: "SIAYAN", label: "SIAYAN" },
  { value: "SIBUCO", label: "SIBUCO" },
  { value: "SIBUTAD", label: "SIBUTAD" },
  { value: "SINDANGAN", label: "SINDANGAN" },
  { value: "SIOCON", label: "SIOCON" },
  { value: "SIRAWAI", label: "SIRAWAI" },
  { value: "TAMPILISAN", label: "TAMPILISAN" },
  { value: "JOSE DALMAN (PONOT)", label: "JOSE DALMAN (PONOT)" },
  { value: "GUTALAC", label: "GUTALAC" },
  { value: "BALIGUIAN", label: "BALIGUIAN" },
  { value: "GODOD", label: "GODOD" },
  { value: "BACUNGAN (Leon T. Postigo)", label: "BACUNGAN (Leon T. Postigo)" },
  { value: "KALAWIT", label: "KALAWIT" },
  { value: "AURORA", label: "AURORA" },
  { value: "BAYOG", label: "BAYOG" },
  { value: "DIMATALING", label: "DIMATALING" },
  { value: "DINAS", label: "DINAS" },
  { value: "DUMALINAO", label: "DUMALINAO" },
  { value: "DUMINGAG", label: "DUMINGAG" },
  { value: "KUMALARANG", label: "KUMALARANG" },
  { value: "LABANGAN", label: "LABANGAN" },
  { value: "LAPUYAN", label: "LAPUYAN" },
  { value: "MAHAYAG", label: "MAHAYAG" },
  { value: "MARGOSATUBIG", label: "MARGOSATUBIG" },
  { value: "MIDSALIP", label: "MIDSALIP" },
  { value: "MOLAVE", label: "MOLAVE" },
  { value: "PAGADIAN CITY (Capital)", label: "PAGADIAN CITY (Capital)" },
  { value: "RAMON MAGSAYSAY (LIARGO)", label: "RAMON MAGSAYSAY (LIARGO)" },
  { value: "SAN MIGUEL", label: "SAN MIGUEL" },
  { value: "SAN PABLO", label: "SAN PABLO" },
  { value: "TABINA", label: "TABINA" },
  { value: "TAMBULIG", label: "TAMBULIG" },
  { value: "TUKURAN", label: "TUKURAN" },
  { value: "ZAMBOANGA CITY", label: "ZAMBOANGA CITY" },
  { value: "LAKEWOOD", label: "LAKEWOOD" },
  { value: "JOSEFINA", label: "JOSEFINA" },
  { value: "PITOGO", label: "PITOGO" },
  {
    value: "SOMINOT (DON MARIANO MARCOS)",
    label: "SOMINOT (DON MARIANO MARCOS)",
  },
  { value: "VINCENZO A. SAGUN", label: "VINCENZO A. SAGUN" },
  { value: "GUIPOS", label: "GUIPOS" },
  { value: "TIGBAO", label: "TIGBAO" },
  { value: "ALICIA", label: "ALICIA" },
  { value: "BUUG", label: "BUUG" },
  { value: "DIPLAHAN", label: "DIPLAHAN" },
  { value: "IMELDA", label: "IMELDA" },
  { value: "IPIL (Capital)", label: "IPIL (Capital)" },
  { value: "KABASALAN", label: "KABASALAN" },
  { value: "MABUHAY", label: "MABUHAY" },
  { value: "MALANGAS", label: "MALANGAS" },
  { value: "NAGA", label: "NAGA" },
  { value: "OLUTANGA", label: "OLUTANGA" },
  { value: "PAYAO", label: "PAYAO" },
  { value: "ROSELLER LIM", label: "ROSELLER LIM" },
  { value: "SIAY", label: "SIAY" },
  { value: "TALUSAN", label: "TALUSAN" },
  { value: "TITAY", label: "TITAY" },
  { value: "TUNGAWAN", label: "TUNGAWAN" },
  { value: "CITY OF ISABELA", label: "CITY OF ISABELA" },
  { value: "BAUNGON", label: "BAUNGON" },
  { value: "DAMULOG", label: "DAMULOG" },
  { value: "DANGCAGAN", label: "DANGCAGAN" },
  { value: "DON CARLOS", label: "DON CARLOS" },
  { value: "IMPASUG-ONG", label: "IMPASUG-ONG" },
  { value: "KADINGILAN", label: "KADINGILAN" },
  { value: "KALILANGAN", label: "KALILANGAN" },
  { value: "KIBAWE", label: "KIBAWE" },
  { value: "KITAOTAO", label: "KITAOTAO" },
  { value: "LANTAPAN", label: "LANTAPAN" },
  { value: "LIBONA", label: "LIBONA" },
  {
    value: "CITY OF MALAYBALAY (Capital)",
    label: "CITY OF MALAYBALAY (Capital)",
  },
  { value: "MALITBOG", label: "MALITBOG" },
  { value: "MANOLO FORTICH", label: "MANOLO FORTICH" },
  { value: "MARAMAG", label: "MARAMAG" },
  { value: "PANGANTUCAN", label: "PANGANTUCAN" },
  { value: "QUEZON", label: "QUEZON" },
  { value: "SAN FERNANDO", label: "SAN FERNANDO" },
  { value: "SUMILAO", label: "SUMILAO" },
  { value: "TALAKAG", label: "TALAKAG" },
  { value: "CITY OF VALENCIA", label: "CITY OF VALENCIA" },
  { value: "CABANGLASAN", label: "CABANGLASAN" },
  { value: "CATARMAN", label: "CATARMAN" },
  { value: "GUINSILIBAN", label: "GUINSILIBAN" },
  { value: "MAHINOG", label: "MAHINOG" },
  { value: "MAMBAJAO (Capital)", label: "MAMBAJAO (Capital)" },
  { value: "SAGAY", label: "SAGAY" },
  { value: "BACOLOD", label: "BACOLOD" },
  { value: "BALOI", label: "BALOI" },
  { value: "BAROY", label: "BAROY" },
  { value: "ILIGAN CITY", label: "ILIGAN CITY" },
  { value: "KAPATAGAN", label: "KAPATAGAN" },
  {
    value: "SULTAN NAGA DIMAPORO (KAROMATAN)",
    label: "SULTAN NAGA DIMAPORO (KAROMATAN)",
  },
  { value: "KAUSWAGAN", label: "KAUSWAGAN" },
  { value: "KOLAMBUGAN", label: "KOLAMBUGAN" },
  { value: "LALA", label: "LALA" },
  { value: "LINAMON", label: "LINAMON" },
  { value: "MAGSAYSAY", label: "MAGSAYSAY" },
  { value: "MAIGO", label: "MAIGO" },
  { value: "MATUNGAO", label: "MATUNGAO" },
  { value: "MUNAI", label: "MUNAI" },
  { value: "NUNUNGAN", label: "NUNUNGAN" },
  { value: "PANTAO RAGAT", label: "PANTAO RAGAT" },
  { value: "POONA PIAGAPO", label: "POONA PIAGAPO" },
  { value: "SALVADOR", label: "SALVADOR" },
  { value: "SAPAD", label: "SAPAD" },
  { value: "TAGOLOAN", label: "TAGOLOAN" },
  { value: "TANGCAL", label: "TANGCAL" },
  { value: "TUBOD (Capital)", label: "TUBOD (Capital)" },
  { value: "PANTAR", label: "PANTAR" },
  { value: "ALORAN", label: "ALORAN" },
  { value: "BALIANGAO", label: "BALIANGAO" },
  { value: "BONIFACIO", label: "BONIFACIO" },
  { value: "CALAMBA", label: "CALAMBA" },
  { value: "CLARIN", label: "CLARIN" },
  { value: "CONCEPCION", label: "CONCEPCION" },
  { value: "JIMENEZ", label: "JIMENEZ" },
  { value: "LOPEZ JAENA", label: "LOPEZ JAENA" },
  { value: "OROQUIETA CITY (Capital)", label: "OROQUIETA CITY (Capital)" },
  { value: "OZAMIS CITY", label: "OZAMIS CITY" },
  { value: "PANAON", label: "PANAON" },
  { value: "PLARIDEL", label: "PLARIDEL" },
  { value: "SAPANG DALAGA", label: "SAPANG DALAGA" },
  { value: "SINACABAN", label: "SINACABAN" },
  { value: "TANGUB CITY", label: "TANGUB CITY" },
  { value: "TUDELA", label: "TUDELA" },
  {
    value: "DON VICTORIANO CHIONGBIAN  (DON MARIANO MARCOS)",
    label: "DON VICTORIANO CHIONGBIAN  (DON MARIANO MARCOS)",
  },
  { value: "ALUBIJID", label: "ALUBIJID" },
  { value: "BALINGASAG", label: "BALINGASAG" },
  { value: "BALINGOAN", label: "BALINGOAN" },
  { value: "BINUANGAN", label: "BINUANGAN" },
  {
    value: "CAGAYAN DE ORO CITY (Capital)",
    label: "CAGAYAN DE ORO CITY (Capital)",
  },
  { value: "CLAVERIA", label: "CLAVERIA" },
  { value: "CITY OF EL SALVADOR", label: "CITY OF EL SALVADOR" },
  { value: "GINGOOG CITY", label: "GINGOOG CITY" },
  { value: "GITAGUM", label: "GITAGUM" },
  { value: "INITAO", label: "INITAO" },
  { value: "JASAAN", label: "JASAAN" },
  { value: "KINOGUITAN", label: "KINOGUITAN" },
  { value: "LAGONGLONG", label: "LAGONGLONG" },
  { value: "LAGUINDINGAN", label: "LAGUINDINGAN" },
  { value: "LIBERTAD", label: "LIBERTAD" },
  { value: "LUGAIT", label: "LUGAIT" },
  { value: "MAGSAYSAY (LINUGOS)", label: "MAGSAYSAY (LINUGOS)" },
  { value: "MANTICAO", label: "MANTICAO" },
  { value: "MEDINA", label: "MEDINA" },
  { value: "NAAWAN", label: "NAAWAN" },
  { value: "OPOL", label: "OPOL" },
  { value: "SALAY", label: "SALAY" },
  { value: "SUGBONGCOGON", label: "SUGBONGCOGON" },
  { value: "TAGOLOAN", label: "TAGOLOAN" },
  { value: "TALISAYAN", label: "TALISAYAN" },
  { value: "VILLANUEVA", label: "VILLANUEVA" },
  { value: "ASUNCION (SAUG)", label: "ASUNCION (SAUG)" },
  { value: "CARMEN", label: "CARMEN" },
  { value: "KAPALONG", label: "KAPALONG" },
  { value: "NEW CORELLA", label: "NEW CORELLA" },
  { value: "CITY OF PANABO", label: "CITY OF PANABO" },
  {
    value: "ISLAND GARDEN CITY OF SAMAL",
    label: "ISLAND GARDEN CITY OF SAMAL",
  },
  { value: "SANTO TOMAS", label: "SANTO TOMAS" },
  { value: "CITY OF TAGUM (Capital)", label: "CITY OF TAGUM (Capital)" },
  { value: "TALAINGOD", label: "TALAINGOD" },
  { value: "BRAULIO E. DUJALI", label: "BRAULIO E. DUJALI" },
  { value: "SAN ISIDRO", label: "SAN ISIDRO" },
  { value: "BANSALAN", label: "BANSALAN" },
  { value: "DAVAO CITY", label: "DAVAO CITY" },
  { value: "CITY OF DIGOS (Capital)", label: "CITY OF DIGOS (Capital)" },
  { value: "HAGONOY", label: "HAGONOY" },
  { value: "KIBLAWAN", label: "KIBLAWAN" },
  { value: "MAGSAYSAY", label: "MAGSAYSAY" },
  { value: "MALALAG", label: "MALALAG" },
  { value: "MATANAO", label: "MATANAO" },
  { value: "PADADA", label: "PADADA" },
  { value: "SANTA CRUZ", label: "SANTA CRUZ" },
  { value: "SULOP", label: "SULOP" },
  { value: "BAGANGA", label: "BAGANGA" },
  { value: "BANAYBANAY", label: "BANAYBANAY" },
  { value: "BOSTON", label: "BOSTON" },
  { value: "CARAGA", label: "CARAGA" },
  { value: "CATEEL", label: "CATEEL" },
  { value: "GOVERNOR GENEROSO", label: "GOVERNOR GENEROSO" },
  { value: "LUPON", label: "LUPON" },
  { value: "MANAY", label: "MANAY" },
  { value: "CITY OF MATI (Capital)", label: "CITY OF MATI (Capital)" },
  { value: "SAN ISIDRO", label: "SAN ISIDRO" },
  { value: "TARRAGONA", label: "TARRAGONA" },
  { value: "COMPOSTELA", label: "COMPOSTELA" },
  { value: "LAAK (SAN VICENTE)", label: "LAAK (SAN VICENTE)" },
  { value: "MABINI (DOÑA ALICIA)", label: "MABINI (DOÑA ALICIA)" },
  { value: "MACO", label: "MACO" },
  { value: "MARAGUSAN (SAN MARIANO)", label: "MARAGUSAN (SAN MARIANO)" },
  { value: "MAWAB", label: "MAWAB" },
  { value: "MONKAYO", label: "MONKAYO" },
  { value: "MONTEVISTA", label: "MONTEVISTA" },
  { value: "NABUNTURAN (Capital)", label: "NABUNTURAN (Capital)" },
  { value: "NEW BATAAN", label: "NEW BATAAN" },
  { value: "PANTUKAN", label: "PANTUKAN" },
  { value: "DON MARCELINO", label: "DON MARCELINO" },
  {
    value: "JOSE ABAD SANTOS (TRINIDAD)",
    label: "JOSE ABAD SANTOS (TRINIDAD)",
  },
  { value: "MALITA", label: "MALITA" },
  { value: "SANTA MARIA", label: "SANTA MARIA" },
  { value: "SARANGANI", label: "SARANGANI" },
  { value: "ALAMADA", label: "ALAMADA" },
  { value: "CARMEN", label: "CARMEN" },
  { value: "KABACAN", label: "KABACAN" },
  {
    value: "CITY OF KIDAPAWAN (Capital)",
    label: "CITY OF KIDAPAWAN (Capital)",
  },
  { value: "LIBUNGAN", label: "LIBUNGAN" },
  { value: "MAGPET", label: "MAGPET" },
  { value: "MAKILALA", label: "MAKILALA" },
  { value: "MATALAM", label: "MATALAM" },
  { value: "MIDSAYAP", label: "MIDSAYAP" },
  { value: "M'LANG", label: "M'LANG" },
  { value: "PIGKAWAYAN", label: "PIGKAWAYAN" },
  { value: "PIKIT", label: "PIKIT" },
  { value: "PRESIDENT ROXAS", label: "PRESIDENT ROXAS" },
  { value: "TULUNAN", label: "TULUNAN" },
  { value: "ANTIPAS", label: "ANTIPAS" },
  { value: "BANISILAN", label: "BANISILAN" },
  { value: "ALEOSAN", label: "ALEOSAN" },
  { value: "ARAKAN", label: "ARAKAN" },
  { value: "BANGA", label: "BANGA" },
  {
    value: "GENERAL SANTOS CITY (DADIANGAS)",
    label: "GENERAL SANTOS CITY (DADIANGAS)",
  },
  {
    value: "CITY OF KORONADAL (Capital)",
    label: "CITY OF KORONADAL (Capital)",
  },
  { value: "NORALA", label: "NORALA" },
  { value: "POLOMOLOK", label: "POLOMOLOK" },
  { value: "SURALLAH", label: "SURALLAH" },
  { value: "TAMPAKAN", label: "TAMPAKAN" },
  { value: "TANTANGAN", label: "TANTANGAN" },
  { value: "T'BOLI", label: "T'BOLI" },
  { value: "TUPI", label: "TUPI" },
  { value: "SANTO NIÑO", label: "SANTO NIÑO" },
  { value: "LAKE SEBU", label: "LAKE SEBU" },
  { value: "BAGUMBAYAN", label: "BAGUMBAYAN" },
  { value: "COLUMBIO", label: "COLUMBIO" },
  { value: "ESPERANZA", label: "ESPERANZA" },
  { value: "ISULAN (Capital)", label: "ISULAN (Capital)" },
  { value: "KALAMANSIG", label: "KALAMANSIG" },
  { value: "LEBAK", label: "LEBAK" },
  { value: "LUTAYAN", label: "LUTAYAN" },
  { value: "LAMBAYONG (MARIANO MARCOS)", label: "LAMBAYONG (MARIANO MARCOS)" },
  { value: "PALIMBANG", label: "PALIMBANG" },
  { value: "PRESIDENT QUIRINO", label: "PRESIDENT QUIRINO" },
  { value: "CITY OF TACURONG", label: "CITY OF TACURONG" },
  { value: "SEN. NINOY AQUINO", label: "SEN. NINOY AQUINO" },
  { value: "ALABEL (Capital)", label: "ALABEL (Capital)" },
  { value: "GLAN", label: "GLAN" },
  { value: "KIAMBA", label: "KIAMBA" },
  { value: "MAASIM", label: "MAASIM" },
  { value: "MAITUM", label: "MAITUM" },
  { value: "MALAPATAN", label: "MALAPATAN" },
  { value: "MALUNGON", label: "MALUNGON" },
  { value: "COTABATO CITY", label: "COTABATO CITY" },
  { value: "TONDO I / II", label: "TONDO I / II" },
  { value: "BINONDO", label: "BINONDO" },
  { value: "QUIAPO", label: "QUIAPO" },
  { value: "SAN NICOLAS", label: "SAN NICOLAS" },
  { value: "SANTA CRUZ", label: "SANTA CRUZ" },
  { value: "SAMPALOC", label: "SAMPALOC" },
  { value: "SAN MIGUEL", label: "SAN MIGUEL" },
  { value: "ERMITA", label: "ERMITA" },
  { value: "INTRAMUROS", label: "INTRAMUROS" },
  { value: "MALATE", label: "MALATE" },
  { value: "PACO", label: "PACO" },
  { value: "PANDACAN", label: "PANDACAN" },
  { value: "PORT AREA", label: "PORT AREA" },
  { value: "SANTA ANA", label: "SANTA ANA" },
  { value: "CITY OF MANDALUYONG", label: "CITY OF MANDALUYONG" },
  { value: "CITY OF MARIKINA", label: "CITY OF MARIKINA" },
  { value: "CITY OF PASIG", label: "CITY OF PASIG" },
  { value: "QUEZON CITY", label: "QUEZON CITY" },
  { value: "CITY OF SAN JUAN", label: "CITY OF SAN JUAN" },
  { value: "CALOOCAN CITY", label: "CALOOCAN CITY" },
  { value: "CITY OF MALABON", label: "CITY OF MALABON" },
  { value: "CITY OF NAVOTAS", label: "CITY OF NAVOTAS" },
  { value: "CITY OF VALENZUELA", label: "CITY OF VALENZUELA" },
  { value: "CITY OF LAS PIÑAS", label: "CITY OF LAS PIÑAS" },
  { value: "CITY OF MAKATI", label: "CITY OF MAKATI" },
  { value: "CITY OF MUNTINLUPA", label: "CITY OF MUNTINLUPA" },
  { value: "CITY OF PARAÑAQUE", label: "CITY OF PARAÑAQUE" },
  { value: "PASAY CITY", label: "PASAY CITY" },
  { value: "PATEROS", label: "PATEROS" },
  { value: "TAGUIG CITY", label: "TAGUIG CITY" },
  { value: "BANGUED (Capital)", label: "BANGUED (Capital)" },
  { value: "BOLINEY", label: "BOLINEY" },
  { value: "BUCAY", label: "BUCAY" },
  { value: "BUCLOC", label: "BUCLOC" },
  { value: "DAGUIOMAN", label: "DAGUIOMAN" },
  { value: "DANGLAS", label: "DANGLAS" },
  { value: "DOLORES", label: "DOLORES" },
  { value: "LA PAZ", label: "LA PAZ" },
  { value: "LACUB", label: "LACUB" },
  { value: "LAGANGILANG", label: "LAGANGILANG" },
  { value: "LAGAYAN", label: "LAGAYAN" },
  { value: "LANGIDEN", label: "LANGIDEN" },
  { value: "LICUAN-BAAY (LICUAN)", label: "LICUAN-BAAY (LICUAN)" },
  { value: "LUBA", label: "LUBA" },
  { value: "MALIBCONG", label: "MALIBCONG" },
  { value: "MANABO", label: "MANABO" },
  { value: "PEÑARRUBIA", label: "PEÑARRUBIA" },
  { value: "PIDIGAN", label: "PIDIGAN" },
  { value: "PILAR", label: "PILAR" },
  { value: "SALLAPADAN", label: "SALLAPADAN" },
  { value: "SAN ISIDRO", label: "SAN ISIDRO" },
  { value: "SAN JUAN", label: "SAN JUAN" },
  { value: "SAN QUINTIN", label: "SAN QUINTIN" },
  { value: "TAYUM", label: "TAYUM" },
  { value: "TINEG", label: "TINEG" },
  { value: "TUBO", label: "TUBO" },
  { value: "VILLAVICIOSA", label: "VILLAVICIOSA" },
  { value: "ATOK", label: "ATOK" },
  { value: "BAGUIO CITY", label: "BAGUIO CITY" },
  { value: "BAKUN", label: "BAKUN" },
  { value: "BOKOD", label: "BOKOD" },
  { value: "BUGUIAS", label: "BUGUIAS" },
  { value: "ITOGON", label: "ITOGON" },
  { value: "KABAYAN", label: "KABAYAN" },
  { value: "KAPANGAN", label: "KAPANGAN" },
  { value: "KIBUNGAN", label: "KIBUNGAN" },
  { value: "LA TRINIDAD (Capital)", label: "LA TRINIDAD (Capital)" },
  { value: "MANKAYAN", label: "MANKAYAN" },
  { value: "SABLAN", label: "SABLAN" },
  { value: "TUBA", label: "TUBA" },
  { value: "TUBLAY", label: "TUBLAY" },
  { value: "BANAUE", label: "BANAUE" },
  { value: "HUNGDUAN", label: "HUNGDUAN" },
  { value: "KIANGAN", label: "KIANGAN" },
  { value: "LAGAWE (Capital)", label: "LAGAWE (Capital)" },
  { value: "LAMUT", label: "LAMUT" },
  { value: "MAYOYAO", label: "MAYOYAO" },
  { value: "ALFONSO LISTA (POTIA)", label: "ALFONSO LISTA (POTIA)" },
  { value: "AGUINALDO", label: "AGUINALDO" },
  { value: "HINGYON", label: "HINGYON" },
  { value: "TINOC", label: "TINOC" },
  { value: "ASIPULO", label: "ASIPULO" },
  { value: "BALBALAN", label: "BALBALAN" },
  { value: "LUBUAGAN", label: "LUBUAGAN" },
  { value: "PASIL", label: "PASIL" },
  { value: "PINUKPUK", label: "PINUKPUK" },
  { value: "RIZAL (LIWAN)", label: "RIZAL (LIWAN)" },
  { value: "CITY OF TABUK (Capital)", label: "CITY OF TABUK (Capital)" },
  { value: "TANUDAN", label: "TANUDAN" },
  { value: "TINGLAYAN", label: "TINGLAYAN" },
  { value: "BARLIG", label: "BARLIG" },
  { value: "BAUKO", label: "BAUKO" },
  { value: "BESAO", label: "BESAO" },
  { value: "BONTOC (Capital)", label: "BONTOC (Capital)" },
  { value: "NATONIN", label: "NATONIN" },
  { value: "PARACELIS", label: "PARACELIS" },
  { value: "SABANGAN", label: "SABANGAN" },
  { value: "SADANGA", label: "SADANGA" },
  { value: "SAGADA", label: "SAGADA" },
  { value: "TADIAN", label: "TADIAN" },
  { value: "CALANASAN (BAYAG)", label: "CALANASAN (BAYAG)" },
  { value: "CONNER", label: "CONNER" },
  { value: "FLORA", label: "FLORA" },
  { value: "KABUGAO (Capital)", label: "KABUGAO (Capital)" },
  { value: "LUNA", label: "LUNA" },
  { value: "PUDTOL", label: "PUDTOL" },
  { value: "SANTA MARCELA", label: "SANTA MARCELA" },
  { value: "CITY OF LAMITAN", label: "CITY OF LAMITAN" },
  { value: "LANTAWAN", label: "LANTAWAN" },
  { value: "MALUSO", label: "MALUSO" },
  { value: "SUMISIP", label: "SUMISIP" },
  { value: "TIPO-TIPO", label: "TIPO-TIPO" },
  { value: "TUBURAN", label: "TUBURAN" },
  { value: "AKBAR", label: "AKBAR" },
  { value: "AL-BARKA", label: "AL-BARKA" },
  { value: "HADJI MOHAMMAD AJUL", label: "HADJI MOHAMMAD AJUL" },
  { value: "UNGKAYA PUKAN", label: "UNGKAYA PUKAN" },
  { value: "HADJI MUHTAMAD", label: "HADJI MUHTAMAD" },
  { value: "TABUAN-LASA", label: "TABUAN-LASA" },
  {
    value: "BACOLOD-KALAWI (BACOLOD GRANDE)",
    label: "BACOLOD-KALAWI (BACOLOD GRANDE)",
  },
  { value: "BALABAGAN", label: "BALABAGAN" },
  { value: "BALINDONG (WATU)", label: "BALINDONG (WATU)" },
  { value: "BAYANG", label: "BAYANG" },
  { value: "BINIDAYAN", label: "BINIDAYAN" },
  { value: "BUBONG", label: "BUBONG" },
  { value: "BUTIG", label: "BUTIG" },
  { value: "GANASSI", label: "GANASSI" },
  { value: "KAPAI", label: "KAPAI" },
  { value: "LUMBA-BAYABAO (MAGUING)", label: "LUMBA-BAYABAO (MAGUING)" },
  { value: "LUMBATAN", label: "LUMBATAN" },
  { value: "MADALUM", label: "MADALUM" },
  { value: "MADAMBA", label: "MADAMBA" },
  { value: "MALABANG", label: "MALABANG" },
  { value: "MARANTAO", label: "MARANTAO" },
  { value: "MARAWI CITY (Capital)", label: "MARAWI CITY (Capital)" },
  { value: "MASIU", label: "MASIU" },
  { value: "MULONDO", label: "MULONDO" },
  { value: "PAGAYAWAN (TATARIKAN)", label: "PAGAYAWAN (TATARIKAN)" },
  { value: "PIAGAPO", label: "PIAGAPO" },
  { value: "POONA BAYABAO (GATA)", label: "POONA BAYABAO (GATA)" },
  { value: "PUALAS", label: "PUALAS" },
  { value: "DITSAAN-RAMAIN", label: "DITSAAN-RAMAIN" },
  { value: "SAGUIARAN", label: "SAGUIARAN" },
  { value: "TAMPARAN", label: "TAMPARAN" },
  { value: "TARAKA", label: "TARAKA" },
  { value: "TUBARAN", label: "TUBARAN" },
  { value: "TUGAYA", label: "TUGAYA" },
  { value: "WAO", label: "WAO" },
  { value: "MAROGONG", label: "MAROGONG" },
  { value: "CALANOGAS", label: "CALANOGAS" },
  { value: "BUADIPOSO-BUNTONG", label: "BUADIPOSO-BUNTONG" },
  { value: "MAGUING", label: "MAGUING" },
  { value: "PICONG (SULTAN GUMANDER)", label: "PICONG (SULTAN GUMANDER)" },
  { value: "LUMBAYANAGUE", label: "LUMBAYANAGUE" },
  { value: "BUMBARAN", label: "BUMBARAN" },
  { value: "TAGOLOAN II", label: "TAGOLOAN II" },
  { value: "KAPATAGAN", label: "KAPATAGAN" },
  { value: "SULTAN DUMALONDONG", label: "SULTAN DUMALONDONG" },
  { value: "LUMBACA-UNAYAN", label: "LUMBACA-UNAYAN" },
  { value: "AMPATUAN", label: "AMPATUAN" },
  { value: "BULDON", label: "BULDON" },
  { value: "BULUAN", label: "BULUAN" },
  { value: "DATU PAGLAS", label: "DATU PAGLAS" },
  { value: "DATU PIANG", label: "DATU PIANG" },
  { value: "DATU ODIN SINSUAT (DINAIG)", label: "DATU ODIN SINSUAT (DINAIG)" },
  {
    value: "SHARIFF AGUAK (MAGANOY) (Capital)",
    label: "SHARIFF AGUAK (MAGANOY) (Capital)",
  },
  { value: "MATANOG", label: "MATANOG" },
  { value: "PAGALUNGAN", label: "PAGALUNGAN" },
  { value: "PARANG", label: "PARANG" },
  { value: "SULTAN KUDARAT (NULING)", label: "SULTAN KUDARAT (NULING)" },
  {
    value: "SULTAN SA BARONGIS (LAMBAYONG)",
    label: "SULTAN SA BARONGIS (LAMBAYONG)",
  },
  { value: "KABUNTALAN (TUMBAO)", label: "KABUNTALAN (TUMBAO)" },
  { value: "UPI", label: "UPI" },
  { value: "TALAYAN", label: "TALAYAN" },
  { value: "SOUTH UPI", label: "SOUTH UPI" },
  { value: "BARIRA", label: "BARIRA" },
  { value: "GEN. S. K. PENDATUN", label: "GEN. S. K. PENDATUN" },
  { value: "MAMASAPANO", label: "MAMASAPANO" },
  { value: "TALITAY", label: "TALITAY" },
  { value: "PAGAGAWAN", label: "PAGAGAWAN" },
  { value: "PAGLAT", label: "PAGLAT" },
  { value: "SULTAN MASTURA", label: "SULTAN MASTURA" },
  { value: "GUINDULUNGAN", label: "GUINDULUNGAN" },
  { value: "DATU SAUDI-AMPATUAN", label: "DATU SAUDI-AMPATUAN" },
  { value: "DATU UNSAY", label: "DATU UNSAY" },
  { value: "DATU ABDULLAH SANGKI", label: "DATU ABDULLAH SANGKI" },
  { value: "RAJAH BUAYAN", label: "RAJAH BUAYAN" },
  { value: "DATU BLAH T. SINSUAT", label: "DATU BLAH T. SINSUAT" },
  { value: "DATU ANGGAL MIDTIMBANG", label: "DATU ANGGAL MIDTIMBANG" },
  { value: "MANGUDADATU", label: "MANGUDADATU" },
  { value: "PANDAG", label: "PANDAG" },
  { value: "NORTHERN KABUNTALAN", label: "NORTHERN KABUNTALAN" },
  { value: "DATU HOFFER AMPATUAN", label: "DATU HOFFER AMPATUAN" },
  { value: "DATU SALIBO", label: "DATU SALIBO" },
  { value: "SHARIFF SAYDONA MUSTAPHA", label: "SHARIFF SAYDONA MUSTAPHA" },
  { value: "INDANAN", label: "INDANAN" },
  { value: "JOLO (Capital)", label: "JOLO (Capital)" },
  { value: "KALINGALAN CALUANG", label: "KALINGALAN CALUANG" },
  { value: "LUUK", label: "LUUK" },
  { value: "MAIMBUNG", label: "MAIMBUNG" },
  {
    value: "HADJI PANGLIMA TAHIL (MARUNGGAS)",
    label: "HADJI PANGLIMA TAHIL (MARUNGGAS)",
  },
  { value: "OLD PANAMAO", label: "OLD PANAMAO" },
  { value: "PANGUTARAN", label: "PANGUTARAN" },
  { value: "PARANG", label: "PARANG" },
  { value: "PATA", label: "PATA" },
  { value: "PATIKUL", label: "PATIKUL" },
  { value: "SIASI", label: "SIASI" },
  { value: "TALIPAO", label: "TALIPAO" },
  { value: "TAPUL", label: "TAPUL" },
  { value: "TONGKIL", label: "TONGKIL" },
  {
    value: "PANGLIMA ESTINO (NEW PANAMAO)",
    label: "PANGLIMA ESTINO (NEW PANAMAO)",
  },
  { value: "LUGUS", label: "LUGUS" },
  { value: "PANDAMI", label: "PANDAMI" },
  { value: "OMAR", label: "OMAR" },
  {
    value: "PANGLIMA SUGALA (BALIMBING)",
    label: "PANGLIMA SUGALA (BALIMBING)",
  },
  { value: "BONGAO (Capital)", label: "BONGAO (Capital)" },
  {
    value: "MAPUN (CAGAYAN DE TAWI-TAWI)",
    label: "MAPUN (CAGAYAN DE TAWI-TAWI)",
  },
  { value: "SIMUNUL", label: "SIMUNUL" },
  { value: "SITANGKAI", label: "SITANGKAI" },
  { value: "SOUTH UBIAN", label: "SOUTH UBIAN" },
  { value: "TANDUBAS", label: "TANDUBAS" },
  { value: "TURTLE ISLANDS", label: "TURTLE ISLANDS" },
  { value: "LANGUYAN", label: "LANGUYAN" },
  { value: "SAPA-SAPA", label: "SAPA-SAPA" },
  { value: "SIBUTU", label: "SIBUTU" },
  { value: "BUENAVISTA", label: "BUENAVISTA" },
  { value: "BUTUAN CITY (Capital)", label: "BUTUAN CITY (Capital)" },
  { value: "CITY OF CABADBARAN", label: "CITY OF CABADBARAN" },
  { value: "CARMEN", label: "CARMEN" },
  { value: "JABONGA", label: "JABONGA" },
  { value: "KITCHARAO", label: "KITCHARAO" },
  { value: "LAS NIEVES", label: "LAS NIEVES" },
  { value: "MAGALLANES", label: "MAGALLANES" },
  { value: "NASIPIT", label: "NASIPIT" },
  { value: "SANTIAGO", label: "SANTIAGO" },
  { value: "TUBAY", label: "TUBAY" },
  { value: "REMEDIOS T. ROMUALDEZ", label: "REMEDIOS T. ROMUALDEZ" },
  { value: "CITY OF BAYUGAN", label: "CITY OF BAYUGAN" },
  { value: "BUNAWAN", label: "BUNAWAN" },
  { value: "ESPERANZA", label: "ESPERANZA" },
  { value: "LA PAZ", label: "LA PAZ" },
  { value: "LORETO", label: "LORETO" },
  { value: "PROSPERIDAD (Capital)", label: "PROSPERIDAD (Capital)" },
  { value: "ROSARIO", label: "ROSARIO" },
  { value: "SAN FRANCISCO", label: "SAN FRANCISCO" },
  { value: "SAN LUIS", label: "SAN LUIS" },
  { value: "SANTA JOSEFA", label: "SANTA JOSEFA" },
  { value: "TALACOGON", label: "TALACOGON" },
  { value: "TRENTO", label: "TRENTO" },
  { value: "VERUELA", label: "VERUELA" },
  { value: "SIBAGAT", label: "SIBAGAT" },
  { value: "ALEGRIA", label: "ALEGRIA" },
  { value: "BACUAG", label: "BACUAG" },
  { value: "BURGOS", label: "BURGOS" },
  { value: "CLAVER", label: "CLAVER" },
  { value: "DAPA", label: "DAPA" },
  { value: "DEL CARMEN", label: "DEL CARMEN" },
  { value: "GENERAL LUNA", label: "GENERAL LUNA" },
  { value: "GIGAQUIT", label: "GIGAQUIT" },
  { value: "MAINIT", label: "MAINIT" },
  { value: "MALIMONO", label: "MALIMONO" },
  { value: "PILAR", label: "PILAR" },
  { value: "PLACER", label: "PLACER" },
  { value: "SAN BENITO", label: "SAN BENITO" },
  { value: "SAN FRANCISCO (ANAO-AON)", label: "SAN FRANCISCO (ANAO-AON)" },
  { value: "SAN ISIDRO", label: "SAN ISIDRO" },
  { value: "SANTA MONICA (SAPAO)", label: "SANTA MONICA (SAPAO)" },
  { value: "SISON", label: "SISON" },
  { value: "SOCORRO", label: "SOCORRO" },
  { value: "SURIGAO CITY (Capital)", label: "SURIGAO CITY (Capital)" },
  { value: "TAGANA-AN", label: "TAGANA-AN" },
  { value: "TUBOD", label: "TUBOD" },
  { value: "BAROBO", label: "BAROBO" },
  { value: "BAYABAS", label: "BAYABAS" },
  { value: "CITY OF BISLIG", label: "CITY OF BISLIG" },
  { value: "CAGWAIT", label: "CAGWAIT" },
  { value: "CANTILAN", label: "CANTILAN" },
  { value: "CARMEN", label: "CARMEN" },
  { value: "CARRASCAL", label: "CARRASCAL" },
  { value: "CORTES", label: "CORTES" },
  { value: "HINATUAN", label: "HINATUAN" },
  { value: "LANUZA", label: "LANUZA" },
  { value: "LIANGA", label: "LIANGA" },
  { value: "LINGIG", label: "LINGIG" },
  { value: "MADRID", label: "MADRID" },
  { value: "MARIHATAG", label: "MARIHATAG" },
  { value: "SAN AGUSTIN", label: "SAN AGUSTIN" },
  { value: "SAN MIGUEL", label: "SAN MIGUEL" },
  { value: "TAGBINA", label: "TAGBINA" },
  { value: "TAGO", label: "TAGO" },
  { value: "CITY OF TANDAG (Capital)", label: "CITY OF TANDAG (Capital)" },
  { value: "BASILISA (RIZAL)", label: "BASILISA (RIZAL)" },
  { value: "CAGDIANAO", label: "CAGDIANAO" },
  { value: "DINAGAT", label: "DINAGAT" },
  { value: "LIBJO (ALBOR)", label: "LIBJO (ALBOR)" },
  { value: "LORETO", label: "LORETO" },
  { value: "SAN JOSE (Capital)", label: "SAN JOSE (Capital)" },
  { value: "TUBAJON", label: "TUBAJON" },
];
