export const province = [
  { value: "ILOCOS NORTE", label: "ILOCOS NORTE" },
  { value: "ILOCOS SUR", label: "ILOCOS SUR" },
  { value: "LA UNION", label: "LA UNION" },
  { value: "PANGASINAN", label: "PANGASINAN" },
  { value: "BATANES", label: "BATANES" },
  { value: "CAGAYAN", label: "CAGAYAN" },
  { value: "ISABELA", label: "ISABELA" },
  { value: "NUEVA VIZCAYA", label: "NUEVA VIZCAYA" },
  { value: "QUIRINO", label: "QUIRINO" },
  { value: "BATAAN", label: "BATAAN" },
  { value: "BULACAN", label: "BULACAN" },
  { value: "NUEVA ECIJA", label: "NUEVA ECIJA" },
  { value: "PAMPANGA", label: "PAMPANGA" },
  { value: "TARLAC", label: "TARLAC" },
  { value: "ZAMBALES", label: "ZAMBALES" },
  { value: "AURORA", label: "AURORA" },
  { value: "BATANGAS", label: "BATANGAS" },
  { value: "CAVITE", label: "CAVITE" },
  { value: "LAGUNA", label: "LAGUNA" },
  { value: "QUEZON", label: "QUEZON" },
  { value: "RIZAL", label: "RIZAL" },
  { value: "MARINDUQUE", label: "MARINDUQUE" },
  { value: "OCCIDENTAL MINDORO", label: "OCCIDENTAL MINDORO" },
  { value: "ORIENTAL MINDORO", label: "ORIENTAL MINDORO" },
  { value: "PALAWAN", label: "PALAWAN" },
  { value: "ROMBLON", label: "ROMBLON" },
  { value: "ALBAY", label: "ALBAY" },
  { value: "CAMARINES NORTE", label: "CAMARINES NORTE" },
  { value: "CAMARINES SUR", label: "CAMARINES SUR" },
  { value: "CATANDUANES", label: "CATANDUANES" },
  { value: "MASBATE", label: "MASBATE" },
  { value: "SORSOGON", label: "SORSOGON" },
  { value: "AKLAN", label: "AKLAN" },
  { value: "ANTIQUE", label: "ANTIQUE" },
  { value: "CAPIZ", label: "CAPIZ" },
  { value: "ILOILO", label: "ILOILO" },
  { value: "NEGROS OCCIDENTAL", label: "NEGROS OCCIDENTAL" },
  { value: "GUIMARAS", label: "GUIMARAS" },
  { value: "BOHOL", label: "BOHOL" },
  { value: "CEBU", label: "CEBU" },
  { value: "NEGROS ORIENTAL", label: "NEGROS ORIENTAL" },
  { value: "SIQUIJOR", label: "SIQUIJOR" },
  { value: "EASTERN SAMAR", label: "EASTERN SAMAR" },
  { value: "LEYTE", label: "LEYTE" },
  { value: "NORTHERN SAMAR", label: "NORTHERN SAMAR" },
  { value: "SAMAR (WESTERN SAMAR)", label: "SAMAR (WESTERN SAMAR)" },
  { value: "SOUTHERN LEYTE", label: "SOUTHERN LEYTE" },
  { value: "BILIRAN", label: "BILIRAN" },
  { value: "ZAMBOANGA DEL NORTE", label: "ZAMBOANGA DEL NORTE" },
  { value: "ZAMBOANGA DEL SUR", label: "ZAMBOANGA DEL SUR" },
  { value: "ZAMBOANGA SIBUGAY", label: "ZAMBOANGA SIBUGAY" },
  { value: "CITY OF ISABELA", label: "CITY OF ISABELA" },
  { value: "BUKIDNON", label: "BUKIDNON" },
  { value: "CAMIGUIN", label: "CAMIGUIN" },
  { value: "LANAO DEL NORTE", label: "LANAO DEL NORTE" },
  { value: "MISAMIS OCCIDENTAL", label: "MISAMIS OCCIDENTAL" },
  { value: "MISAMIS ORIENTAL", label: "MISAMIS ORIENTAL" },
  { value: "DAVAO DEL NORTE", label: "DAVAO DEL NORTE" },
  { value: "DAVAO DEL SUR", label: "DAVAO DEL SUR" },
  { value: "DAVAO ORIENTAL", label: "DAVAO ORIENTAL" },
  { value: "COMPOSTELA VALLEY", label: "COMPOSTELA VALLEY" },
  { value: "DAVAO OCCIDENTAL", label: "DAVAO OCCIDENTAL" },
  { value: "COTABATO (NORTH COTABATO)", label: "COTABATO (NORTH COTABATO)" },
  { value: "SOUTH COTABATO", label: "SOUTH COTABATO" },
  { value: "SULTAN KUDARAT", label: "SULTAN KUDARAT" },
  { value: "SARANGANI", label: "SARANGANI" },
  { value: "COTABATO CITY", label: "COTABATO CITY" },
  {
    value: "NCR, CITY OF MANILA, FIRST DISTRICT",
    label: "NCR, CITY OF MANILA, FIRST DISTRICT",
  },
  { value: "CITY OF MANILA", label: "CITY OF MANILA" },
  { value: "NCR, SECOND DISTRICT", label: "NCR, SECOND DISTRICT" },
  { value: "NCR, THIRD DISTRICT", label: "NCR, THIRD DISTRICT" },
  { value: "NCR, FOURTH DISTRICT", label: "NCR, FOURTH DISTRICT" },
  { value: "ABRA", label: "ABRA" },
  { value: "BENGUET", label: "BENGUET" },
  { value: "IFUGAO", label: "IFUGAO" },
  { value: "KALINGA", label: "KALINGA" },
  { value: "MOUNTAIN PROVINCE", label: "MOUNTAIN PROVINCE" },
  { value: "APAYAO", label: "APAYAO" },
  { value: "BASILAN", label: "BASILAN" },
  { value: "LANAO DEL SUR", label: "LANAO DEL SUR" },
  { value: "MAGUINDANAO", label: "MAGUINDANAO" },
  { value: "SULU", label: "SULU" },
  { value: "TAWI-TAWI", label: "TAWI-TAWI" },
  { value: "AGUSAN DEL NORTE", label: "AGUSAN DEL NORTE" },
  { value: "AGUSAN DEL SUR", label: "AGUSAN DEL SUR" },
  { value: "SURIGAO DEL NORTE", label: "SURIGAO DEL NORTE" },
  { value: "SURIGAO DEL SUR", label: "SURIGAO DEL SUR" },
  { value: "DINAGAT ISLANDS", label: "DINAGAT ISLANDS" },
];
